/- R-1 witness: a completed outline that never presents the emitted
   `def goal :` line. The goal body below is a verbatim copy of the
   fresh emission, but declared under the doubled harness namespace so
   the old per-def drift probe resolved its LHS to THIS def and passed
   while nothing bound the closer to the real goal. Must be rejected. -/
/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean -/

noncomputable def GeneratedHarness.GeneratedHarness.goal : Prop :=
  (x : Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) -> (y : Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) -> let x := (Pure.pure x);
  let y := (Pure.pure y); @Eq.{1} (Except String Bool) (Bind.bind (Bind.bind x
  (fun v_1 => Bind.bind y (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1 v_2))))
  (fun v_1' => Bind.bind (Bind.bind y (fun v_1 => Bind.bind x
  (fun v_2 => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1 v_2))))
  (fun v_2' => Pure.pure (bvEq (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1' v_2')))) (Pure.pure
  Bool.true)

