/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean -/

noncomputable def goal : Prop :=
  (x : PairType (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType))) ->
  let x := (Pure.pure x); let x__ := (Bind.bind x (fun v_2 => Pure.pure
  (Pair_fst (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)));
  let x__' := (Bind.bind (Bind.bind (Bind.bind x (fun v_2 => Pure.pure (Pair_snd
  (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')))
  (fun v_2'' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType v_2'')));
  let x__'' := (Bind.bind (Bind.bind x (fun v_2 => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')));
  let x__''' := (Bind.bind (vecSequenceM 4 (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)
  #v[let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) x__
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  h_bounds_, let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) x__
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  h_bounds_, let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) x__
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  h_bounds_, let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) x__
  CryptolToLean.SAWCorePrimitives.zero_macro h_bounds_]) (fun v_2'' => Bind.bind
  (Bind.bind x__' (fun v_2' => Bind.bind (Bind.bind x__'' (fun v_2 => Pure.pure
  (@PairType.PairValue (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType v_2
  UnitType.Unit))) (fun v_3 => Pure.pure (@PairType.PairValue (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2' v_3))))
  (fun v_3' => Pure.pure (@PairType.PairValue (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2''
  v_3')))); let x__'''' := (Bind.bind (genWithBoundsM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)
  (fun (i : Nat) (h_gen_bounds_ : LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) => let h_bounds_obligation_ : (Prop) := (LT.lt
  (subNat (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) i)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) x__ (subNat
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) i) h_bounds_))
  (fun v_2'' => Bind.bind (Bind.bind x__' (fun v_2' => Bind.bind (Bind.bind
  x__'' (fun v_2 => Pure.pure (@PairType.PairValue (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType v_2
  UnitType.Unit))) (fun v_3 => Pure.pure (@PairType.PairValue (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2' v_3))))
  (fun v_3' => Pure.pure (@PairType.PairValue (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2''
  v_3')))); @Eq.{1} (Except String Bool) (CryptolToLean.SAWCorePreludeExtra.iteM
  Bool (foldrM Bool Bool (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (fun (b1 : Except String
  Bool) (b2 : Except String Bool) => CryptolToLean.SAWCorePreludeExtra.iteM Bool
  b1 b2 (Pure.pure Bool.false)) (Pure.pure Bool.true) (genWithBoundsM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) Bool
  (fun (i : Nat) (h_gen_bounds_ : LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) => let x__''''' := (Bind.bind x
  (fun v_2 => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)));
  let x__'''''' := (Bind.bind (Bind.bind (Bind.bind x (fun v_2 => Pure.pure
  (Pair_snd (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')))
  (fun v_2'' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType v_2'')));
  let x__''''''' := (Bind.bind (Bind.bind x (fun v_2 => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')));
  Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) (Bind.bind x__'''
  (fun v_2 => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2))) i
  h_bounds_) (fun v_1 => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  i (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) (Bind.bind x__''''
  (fun v_2 => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2))) i
  h_bounds_) (fun v_2' => Pure.pure (bvEq
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1 v_2'))))))
  (CryptolToLean.SAWCorePreludeExtra.iteM Bool (Bind.bind (Bind.bind (Bind.bind
  x__''' (fun v_2 => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')))
  (fun v_1 => Bind.bind (Bind.bind (Bind.bind x__'''' (fun v_2 => Pure.pure
  (Pair_snd (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')))
  (fun v_2'' => Pure.pure (bvEq (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) v_1 v_2''))))
  (CryptolToLean.SAWCorePreludeExtra.iteM Bool (Bind.bind (Bind.bind (Bind.bind
  (Bind.bind x__''' (fun v_2 => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')))
  (fun v_2'' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType v_2'')))
  (fun v_1 => Bind.bind (Bind.bind (Bind.bind (Bind.bind x__''''
  (fun v_2 => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType)) v_2)))
  (fun v_2' => Pure.pure (Pair_snd (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType) v_2')))
  (fun v_2'' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool) UnitType v_2'')))
  (fun v_2''' => Pure.pure (bvEq (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) v_1 v_2''')))) (Pure.pure
  Bool.true) (Pure.pure Bool.false)) (Pure.pure Bool.false)) (Pure.pure
  Bool.false)) (Pure.pure Bool.true)

-- The obligation is the tuple-structured swap postcondition:
--   ( reverse x.0, x.2, x.1 )  ==  ( [x.0@3, x.0@2, x.0@1, x.0@0], x.2, x.1 )
-- for a symbolic struct value x : ([4][8],[16],[16]). We destructure x into
-- its three components, normalize the reverse indices (3 - (3 - i) = i) so the
-- spec-side `reverse` reindexing lines up literally with the C-side accessor,
-- and reduce the componentwise fold of `bvEq` over identical components via
-- `bvEq_refl`. Every array access is at a concrete in-range index, so the
-- checked-indexing machinery unfolds cleanly. maxRecDepth is raised (NOT
-- maxHeartbeats) because the nested PairType projections plus the size-4
-- reverse fold nest the reduction deeply.
set_option maxRecDepth 8000 in
theorem goal_holds : goal := by
  intro x
  obtain ⟨xs, y, z, _u⟩ := x
  have h_double_rev_idx : ∀ i : Fin 4, 3 - (3 - (i : Nat)) = (i : Nat) := by
    intro i; omega
  have hfin0 : ((0 : Fin 4) : Nat) = 0 := rfl
  have hfin1 : ((1 : Fin 4) : Nat) = 1 := rfl
  have hfin2 : ((2 : Fin 4) : Nat) = 2 := rfl
  have hfin3 : ((3 : Fin 4) : Nat) = 3 := rfl
  simp +decide [genWithBoundsM, atWithProof_checkedM, atRuntimeCheckedM,
    foldrM, subNat, vecSequenceM, Vector.ofFnM_succ, Vector.ofFnM_zero,
    intLe, intSub, intNeg, intToNat, natToInt,
    hfin0, hfin1, hfin2, hfin3,
    Pair_fst, Pair_snd,
    CryptolToLean.SAWCorePreludeExtra.iteM, h_double_rev_idx, bvEq_refl,
    Pure.pure, Bind.bind, Except.pure, Except.bind]