{- |
Module      : CryptolSAWCore.Simpset
Copyright   : Galois, Inc. 2018
License     : BSD3
Maintainer  : huffman@galois.com
Stability   : experimental
Portability : non-portable (language extensions)
-}

{-# LANGUAGE OverloadedStrings #-}

module CryptolSAWCore.Simpset
  ( mkCryptolSimpset
  ) where

import SAWCore.Module (moduleDefs, Def(..))
import SAWCore.Name
import SAWCore.QualName (QualName)
import SAWCore.Rewriter
import SAWCore.SharedTerm

-- | Build a 'Simpset' with rewrite rules that can simplify terms
-- generated by the Cryptol-to-SAWCore translator, reducing them to
-- more basic operations and types from the SAWCore prelude.
--
-- The Cryptol translator generates coercions for non-trivial type
-- equalities proved by the Cryptol typechecker.
-- We include rewrite rules that can simplify them away after types
-- are instantiated and the coercions become trivial.

mkCryptolSimpset :: SharedContext -> IO (Simpset a)
mkCryptolSimpset sc =
  do m <- scFindModule sc cryptolModuleName
     scSimpset sc (cryptolDefs m) idents []
  where
    cryptolDefs m = filter (not . excluded) $ moduleDefs m
    excluded d =
      toQualName (nameInfo (defName d)) `elem` excludedNames
    idents =
      [ "Prelude.coerce_same"
      , "Prelude.unsafeCoerce_same"
      , "Prelude.headRecord_RecordValue"
      , "Prelude.tailRecord_RecordValue"
      ]

cryptolModuleName :: ModuleName
cryptolModuleName = mkModuleName ["Cryptol"]

excludedNames :: [QualName]
excludedNames =
  [ "Prelude.fix"
  , "Cryptol.pair_cong"
  , "Cryptol.seq_cong"
  , "Cryptol.pair_cong1"
  , "Cryptol.pair_cong2"
  , "Cryptol.seq_cong1"
  , "Cryptol.fun_cong"
  , "Cryptol.seq_TCNum"
  , "Cryptol.seq_TCInf"
  , "Cryptol.PZero"
  , "Cryptol.PLiteral"
  , "Cryptol.PLogic"
  , "Cryptol.PRing"
  , "Cryptol.PIntegral"
  , "Cryptol.PField"
  , "Cryptol.PRound"
  , "Cryptol.PEq"
  , "Cryptol.PCmp"
  , "Cryptol.PSignedCmp"
  , "Cryptol.ecEq"
  ]
