/- Verbatim copy of `out/invol_prove0.lean`, wrapped in a namespace
so the two demo emitted-files (invol, eq) both defining `goal` can
co-exist in one Lake build. Regenerate by copying `out/invol_prove0.lean`
into this file and re-wrapping in the `namespace PointShiftInvolDemo`
block. -/

/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

namespace InvolDemo

/- Code generated by saw-core-lean -/

noncomputable def goal : Prop :=
  (xs : CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8
  Bool)) -> @Eq Bool (foldr Bool Bool 4
  (fun (b1 : Bool) (b2 : Bool) => CryptolToLean.SAWCorePreludeExtra.ite Bool b1
  b2 Bool.false) Bool.true (gen 4 Bool (fun (i : Nat) => bvEq 8 (atWithDefault 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (error_unrestricted
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) "at: index out of bounds") (coerce
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool))
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool))
  (@Eq.rec Num (Num.TCNum 4) (fun (y' : Num) (eq' : @Eq Num (Num.TCNum (subNat 4
  0)) y') => @Eq Type (CryptolToLean.SAWCoreVectors.Vec 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (@Num.rec (fun (num : Num) => Type)
  (fun (n : Nat) => CryptolToLean.SAWCoreVectors.Vec n
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (Stream
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) y')) (@Eq.refl Type
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8
  Bool))) (Num.TCNum 4) (unsafeAssert Num (Num.TCNum 4) (Num.TCNum 4))) (gen 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (fun (i' : Nat) => @Either.rec Nat
  Nat (fun (p : Either Nat Nat) => CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  (fun (i'' : Nat) => atWithDefault 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  (error_unrestricted (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  "at: index out of bounds") (coerce (CryptolToLean.SAWCoreVectors.Vec 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (CryptolToLean.SAWCoreVectors.Vec 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (@Eq.rec Num (Num.TCNum 4)
  (fun (y' : Num) (eq' : @Eq Num (Num.TCNum (subNat 4 0)) y') => @Eq Type
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool))
  (@Num.rec (fun (num : Num) => Type)
  (fun (n : Nat) => CryptolToLean.SAWCoreVectors.Vec n
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (Stream
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) y')) (@Eq.refl Type
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8
  Bool))) (Num.TCNum 4) (unsafeAssert Num (Num.TCNum 4) (Num.TCNum 4))) (gen 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (fun (i''' : Nat) => @Either.rec Nat
  Nat (fun (p : Either Nat Nat) => CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  (fun (i'''' : Nat) => atWithDefault 4 (CryptolToLean.SAWCoreVectors.Vec 8
  Bool) (error_unrestricted (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  "at: index out of bounds") xs i'''') (fun (_ : Nat) => atWithDefault 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (error_unrestricted
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) "at: index out of bounds") xs 0)
  (CryptolToLean.SAWCorePreludeExtra.ite (Either Nat Nat) (intLe (natToInt 0)
  (intSub (natToInt 3) (atWithDefault 4 Int (error_unrestricted Int
  "at: index out of bounds") (gen 4 Int (fun (i'''' : Nat) => natToInt (addNat
  i'''' 0))) i'''))) (@Either.Left Nat Nat (intToNat (intSub (natToInt 3)
  (atWithDefault 4 Int (error_unrestricted Int "at: index out of bounds") (gen 4
  Int (fun (i'''' : Nat) => natToInt (addNat i'''' 0))) i''')))) (@Either.Right
  Nat Nat (intToNat (intNeg (intSub (natToInt 3) (atWithDefault 4 Int
  (error_unrestricted Int "at: index out of bounds") (gen 4 Int
  (fun (i'''' : Nat) => natToInt (addNat i'''' 0))) i'''))))))))) i'')
  (fun (_ : Nat) => atWithDefault 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  (error_unrestricted (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  "at: index out of bounds") (coerce (CryptolToLean.SAWCoreVectors.Vec 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (CryptolToLean.SAWCoreVectors.Vec 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (@Eq.rec Num (Num.TCNum 4)
  (fun (y' : Num) (eq' : @Eq Num (Num.TCNum (subNat 4 0)) y') => @Eq Type
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool))
  (@Num.rec (fun (num : Num) => Type)
  (fun (n : Nat) => CryptolToLean.SAWCoreVectors.Vec n
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) (Stream
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool)) y')) (@Eq.refl Type
  (CryptolToLean.SAWCoreVectors.Vec 4 (CryptolToLean.SAWCoreVectors.Vec 8
  Bool))) (Num.TCNum 4) (unsafeAssert Num (Num.TCNum 4) (Num.TCNum 4))) (gen 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (fun (i'' : Nat) => @Either.rec Nat
  Nat (fun (p : Either Nat Nat) => CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  (fun (i''' : Nat) => atWithDefault 4 (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  (error_unrestricted (CryptolToLean.SAWCoreVectors.Vec 8 Bool)
  "at: index out of bounds") xs i''') (fun (_' : Nat) => atWithDefault 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (error_unrestricted
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) "at: index out of bounds") xs 0)
  (CryptolToLean.SAWCorePreludeExtra.ite (Either Nat Nat) (intLe (natToInt 0)
  (intSub (natToInt 3) (atWithDefault 4 Int (error_unrestricted Int
  "at: index out of bounds") (gen 4 Int (fun (i''' : Nat) => natToInt (addNat
  i''' 0))) i''))) (@Either.Left Nat Nat (intToNat (intSub (natToInt 3)
  (atWithDefault 4 Int (error_unrestricted Int "at: index out of bounds") (gen 4
  Int (fun (i''' : Nat) => natToInt (addNat i''' 0))) i'')))) (@Either.Right Nat
  Nat (intToNat (intNeg (intSub (natToInt 3) (atWithDefault 4 Int
  (error_unrestricted Int "at: index out of bounds") (gen 4 Int
  (fun (i''' : Nat) => natToInt (addNat i''' 0))) i''))))))))) 0)
  (CryptolToLean.SAWCorePreludeExtra.ite (Either Nat Nat) (intLe (natToInt 0)
  (intSub (natToInt 3) (atWithDefault 4 Int (error_unrestricted Int
  "at: index out of bounds") (gen 4 Int (fun (i'' : Nat) => natToInt (addNat i''
  0))) i'))) (@Either.Left Nat Nat (intToNat (intSub (natToInt 3) (atWithDefault
  4 Int (error_unrestricted Int "at: index out of bounds") (gen 4 Int
  (fun (i'' : Nat) => natToInt (addNat i'' 0))) i')))) (@Either.Right Nat Nat
  (intToNat (intNeg (intSub (natToInt 3) (atWithDefault 4 Int
  (error_unrestricted Int "at: index out of bounds") (gen 4 Int
  (fun (i'' : Nat) => natToInt (addNat i'' 0))) i'))))))))) i) (atWithDefault 4
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) (error_unrestricted
  (CryptolToLean.SAWCoreVectors.Vec 8 Bool) "at: index out of bounds") xs i))))
  Bool.true

-- The `theorem goal_holds := by sorry` stub that saw-core-lean
-- would emit here is omitted in this demo. Proofs/Invol.lean
-- supplies the actual discharge, which is checked on `lake build`.

end InvolDemo