enable_experimental;
MODULE_SKEL <- module_skeleton MODULE;

baz_skel <- function_skeleton MODULE_SKEL "baz";
let baz_spec = do {
  skeleton_globals_pre MODULE_SKEL;
  prestate <- skeleton_prestate baz_skel;
  skeleton_exec prestate;
  poststate <- skeleton_poststate baz_skel prestate;
  skeleton_globals_post MODULE_SKEL;
};
baz_override <- llvm_verify MODULE "baz" [] false baz_spec z3;

bar_skel <- function_skeleton MODULE_SKEL "bar";
let bar_spec = do {
  skeleton_globals_pre MODULE_SKEL;
  prestate <- skeleton_prestate bar_skel;
  skeleton_exec prestate;
  poststate <- skeleton_poststate bar_skel prestate;
  skeleton_globals_post MODULE_SKEL;
};
bar_override <- llvm_verify MODULE "bar" [baz_override] false bar_spec z3;


