/- B1 witness (0.02 release-gate audit, 2026-07-29, CRITICAL).

   A completed outline carrying a SELF-ERASING metaprogram. The goal
   body below is a verbatim copy of the fresh emission, so the outline
   is otherwise honest; what makes it a witness is the `run_cmd` at
   the end.

   The SAW caller stages a completed outline as BOTH completed.lean
   and Emitted.lean, and the trust kernel's first Lean action used to
   be compiling Emitted.lean. So this file was ELABORATED before any
   gate read it. Elaboration executes commands: the `run_cmd` rewrote
   completed.lean to a clean copy and Generated.lean — the drift
   check's authority, the only thing binding this `def goal` to the
   SAW obligation — to agree with whatever goal the user chose. The
   lint 140 lines later then read the clean copy and passed.

   With the gates moved ahead of the first elaboration, the lint reads
   THIS text and the run is refused:
   CHECK-FAIL: axiom-or-macro-decl-in-user-file.

   This row pins the PRODUCT path. The kernel selftest's `b1elab`
   case pins the same property at the script level; this one pins the
   wiring the script-level case cannot see. -/
/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean -/

noncomputable def GeneratedHarness.GeneratedHarness.goal : Prop :=
  (x : Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) -> (y : Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) -> let x := (Pure.pure x);
  let y := (Pure.pure y); @Eq.{1} (Except String Bool) (Bind.bind (Bind.bind x
  (fun v_1 => Bind.bind y (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1 v_2))))
  (fun v_1' => Bind.bind (Bind.bind y (fun v_1 => Bind.bind x
  (fun v_2 => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1 v_2))))
  (fun v_2' => Pure.pure (bvEq (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1' v_2')))) (Pure.pure
  Bool.true)

open Lean Elab Command in
run_cmd do
  let clean := "import CryptolToLean\n\nnoncomputable def goal : Prop := True\n"
  let root : System.FilePath := ".replay-stage"
  if (← root.pathExists) then
    for d in (← root.readDir) do
      let c := d.path / "completed.lean"
      if (← c.pathExists) then IO.FS.writeFile c clean
