/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors

/- Code generated by saw-core-lean -/
/-
R3b ACCEPTANCE DISCHARGE - rec_ones realized, obligation closed.

Completed outline of the generated module: the element function is
named via RecOnesDischarge.streamFn (definitionally the emitted
let-bound lambda) and the single h_stream_prod_ placeholder is
replaced by the PROVEN per-instance obligation (faithful + lookback,
fifth-audit amendments 2-3, stated against the verbatim wrapped
element function at the realization input). The old path's DOUBLE
by-stub obligation (mkStream totality + fix uniqueness) is gone -
this row is the fifth-audit acceptance gate: no placeholder residue
in the discharge tier.
-/

namespace RecOnesDischarge

open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCorePreludeProofs

/-- The emitted element function, verbatim from the generated module
(definitionally the let-bound stream_fn_). -/
noncomputable def streamFn :
    Except String (Stream Bool) → Nat → Except String Bool :=
  (fun (allTrue : Except String (Stream
    Bool)) => fun (i : Nat) => atWithDefaultM
    (CryptolToLean.SAWCorePrimitives.natPos_macro
    CryptolToLean.SAWCorePrimitives.one_macro) Bool (Bind.bind allTrue
    (fun scrut_ => @Stream.rec Bool (fun (strm' : Stream Bool) => Except String
    Bool) (fun (s : Nat -> Bool) => let s := (fun η_arg_0 => Pure.pure (s
    η_arg_0)); s (subNat i (CryptolToLean.SAWCorePrimitives.natPos_macro
    CryptolToLean.SAWCorePrimitives.one_macro))) scrut_)) (vecSequenceM 1 Bool
    #v[Pure.pure Bool.true]) i)

/-- H_prod-stream for rec_ones: both fields by unfolding the concrete
element function (fifth-audit amendments 2-3 — stated against the
verbatim wrapped element function at the realization input). -/
theorem rec_ones_h_prod :
    saw_stream_single_productive Bool Bool.true
      (fun prev_ => prev_) streamFn := by
  constructor
  · intro i
    cases i with
    | zero =>
      unfold streamFn
      simp [Pure.pure, Bind.bind, Except.bind, Except.pure,
            atWithDefaultM, vecSequenceM_singleton_ok, streamIdx,
            saw_stream_unfold]
      rfl
    | succ k =>
      unfold streamFn
      simp [Pure.pure, Bind.bind, Except.bind, Except.pure,
            atWithDefaultM, vecSequenceM_singleton_ok, streamIdx,
            saw_stream_unfold, subNat_eq_natSub]
  · intro t₁ t₂ i hpre
    cases t₁ with
    | MkStream f₁ =>
      cases t₂ with
      | MkStream f₂ =>
        cases i with
        | zero => rfl
        | succ k =>
          have hk := hpre k (by omega)
          simp only [streamIdx] at hk
          show streamFn (Pure.pure (Stream.MkStream f₁)) (k + 1) =
            streamFn (Pure.pure (Stream.MkStream f₂)) (k + 1)
          unfold streamFn
          simp [Pure.pure, Bind.bind, Except.bind, Except.pure,
                atWithDefaultM, vecSequenceM_singleton_ok,
                subNat_eq_natSub, hk]

end RecOnesDischarge

namespace RecOnes
  saw_ctor_order CryptolToLean.SAWCorePrimitives.Stream [CryptolToLean.SAWCorePrimitives.Stream.MkStream]

  noncomputable def allTrue : Except String (Stream Bool) :=
    let stream_fn_ := (RecOnesDischarge.streamFn);
    let h_stream_prod_obligation_ : (Prop) := (saw_stream_single_productive Bool
    Bool.true (fun prev_ => prev_) stream_fn_);
    let h_stream_prod_ : (h_stream_prod_obligation_) := ((RecOnesDischarge.rec_ones_h_prod));
    saw_stream_realize Bool Bool.true (fun prev_ => prev_) stream_fn_
    h_stream_prod_

end RecOnes