{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : SAWCoreLean.Lean
Copyright   : Galois, Inc. 2026
License     : BSD3
Maintainer  : saw@galois.com
Stability   : experimental
Portability : portable

Top-level entry points for the SAWCore-to-Lean translator. Mirrors
"SAWCoreRocq.Rocq" (preamble / @translateTermAsDeclImports@) but with
a minimal preamble suited to Lean's import syntax.
-}

module SAWCoreLean.Lean
  ( TranslationConfiguration(..)
  , preamble
  , translateTermAsDeclImports
  , ppTranslationError
  ) where

import           Prettyprinter

import qualified Language.Lean.AST        as Lean
import           SAWCore.SharedTerm

import           SAWCoreLean.Monad
import qualified SAWCoreLean.Term         as TermTranslation

-- | Imports emitted at the top of every generated file. The modules
-- referenced here will land under @saw-core-lean/lean/CryptolToLean/@
-- once the support library exists (Phase 1). Listing them now fixes
-- the expected layout so generated output is stable from the start.
preamble :: TranslationConfiguration -> Doc ann
preamble _configuration = vsep
  [ "/- Mandatory imports from saw-core-lean -/"
  , "import CryptolToLean.SAWCoreScaffolding"
  , "import CryptolToLean.SAWCoreVectors"
  , "import CryptolToLean.SAWCoreBitvectors"
  , "import CryptolToLean.SAWCorePrelude"
  , "import CryptolToLean.CryptolPrimitivesForSAWCore"
  , ""
  , "open CryptolToLean"
  , ""
  , "/- Code generated by saw-core-lean -/"
  ]

-- | Translate a single SAWCore 'Term' (with its type) to a Lean @def@
-- with the given name, prepended by the standard preamble.
translateTermAsDeclImports ::
  TranslationConfiguration -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann)
translateTermAsDeclImports configuration name t tp = do
  doc <- TermTranslation.translateDefDoc configuration name t tp
  pure (vcat [preamble configuration, hardline <> doc])
