{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : SAWCoreLean.Lean
Copyright   : Galois, Inc. 2026
License     : BSD3
Maintainer  : saw@galois.com
Stability   : experimental
Portability : portable

Top-level entry points for the SAWCore-to-Lean translator. Mirrors
"SAWCoreRocq.Rocq" (preamble / @translateTermAsDeclImports@) but with
a minimal preamble suited to Lean's import syntax.
-}

module SAWCoreLean.Lean
  ( TranslationConfiguration(..)
  , preamble
  , translateTermAsDeclImports
  , translateGoalAsDeclImports
  , translateGoalAsDeclImportsWithArity
  , translateGoalAsDeclImportsWithTelescope
  , TermTranslation.TelescopeFp(..)
  , TermTranslation.telescopeFpMismatch
  , translateCryptolModule
  , translateSAWModule
  , moduleDeclName
  , ppTranslationError
  ) where

import qualified Data.Text                as Text
import           Prettyprinter

import qualified Language.Lean.AST        as Lean
import qualified Language.Lean.Pretty     as Lean
import           SAWCore.Module           (Def(..), ModuleDecl(..),
                                           ModuleMap, DataType(..),
                                           Module, moduleName, moduleDecls)
import           SAWCore.Name             (ModuleName, nameInfo, toShortName,
                                           moduleNamePieces)
import           SAWCore.SharedTerm

import           CryptolSAWCore.TypedTerm (CryptolModule)
import           CryptolSAWCore.Cryptol   (CryptolEnv)

import qualified SAWCoreLean.CryptolModule as CMT
import           SAWCoreLean.Monad
import qualified SAWCoreLean.SAWModule    as SAWModuleTranslation
import           SAWCoreLean.SpecialTreatment (escapeIdent,
                                               implicitlyOpenedModules,
                                               translateModuleName)
import qualified SAWCoreLean.Term         as TermTranslation

-- | Imports emitted at the top of every generated file.
--
-- The @CryptolToLean@ root module (under @saw-core-lean/lean/@)
-- re-exports the handwritten support modules. We additionally
-- @open@ the modules listed in 'implicitlyOpenedModules' so the
-- translator can emit bare short names for the dominant primitive
-- namespace (currently 'CryptolToLean.SAWCorePrimitives').
--
-- Pass 'True' for 'includeProofOpens' to additionally open the
-- @*_proofs@ namespaces. Used by goal emission so the emitted
-- file is self-contained: a user who replaces the @sorry@ in
-- @goal_holds@ in-place can reference @bvAdd_comm@,
-- @gen_atWithDefault_double_reverse@, etc. without restating
-- @open@s. Note: Lean's @open@s are file-local, so a separate
-- discharge file using @import Emitted@ still needs its own
-- @open@s. Term emission passes 'False' — generated module files
-- don't need proof helpers in scope.
preamble :: Bool -> TranslationConfiguration -> Doc ann
preamble includeProofOpens _configuration = vsep $
  [ "/- Mandatory imports from saw-core-lean -/"
  , "import CryptolToLean"
  , ""
  ] ++ openLines ++ proofOpenLines ++
  [ ""
  , "/- Code generated by saw-core-lean -/"
  ]
  where
    openLines =
      [ "open" <+> prettyModule m
      | m <- implicitlyOpenedModules
      ]
    proofOpenLines
      | includeProofOpens =
          [ "open CryptolToLean.SAWCoreBitvectorsProofs"
          , "open CryptolToLean.SAWCorePreludeProofs"
          ]
      | otherwise = []
    prettyModule m =
      pretty (Text.intercalate "." (moduleNamePieces m))

-- | Translate a single SAWCore 'Term' (with its type) to a Lean @def@
-- with the given name, prepended by the standard preamble.
translateTermAsDeclImports ::
  TranslationConfiguration -> ModuleMap -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann)
translateTermAsDeclImports configuration mm name t tp = do
  doc <- TermTranslation.translateDefDoc configuration mm name t tp
  pure (vcat [preamble False configuration, hardline <> doc])

-- | Translate a SAWCore proof goal (a 'Term' of type @Prop@) to a
-- Lean file containing two declarations: a @def@ naming the
-- proposition, and a @theorem <name>_holds : <name> := by sorry@
-- stub the user discharges by hand. Mirrors the design-doc §3.2
-- shape of 'offline_lean' output.
translateGoalAsDeclImports ::
  TranslationConfiguration -> ModuleMap -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann)
translateGoalAsDeclImports configuration mm name t tp =
  fst <$> translateGoalAsDeclImportsWithArity configuration mm name t tp

-- | 'translateGoalAsDeclImports' plus the emitted goal's Pi-spine
-- arity, for the emission telescope pin (the caller compares it
-- against the SAWCore-side count and refuses on mismatch).
translateGoalAsDeclImportsWithArity ::
  TranslationConfiguration -> ModuleMap -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann, Int)
translateGoalAsDeclImportsWithArity configuration mm name t tp =
  (\(d, a, _) -> (d, a)) <$>
    translateGoalAsDeclImportsWithTelescope configuration mm name t tp

-- | Like 'translateGoalAsDeclImportsWithArity' but also returns the
-- emitted goal Pi spine's binder TYPES (2026-07-18 replay hardening:
-- the binder-type half of the goal-telescope pin).
translateGoalAsDeclImportsWithTelescope ::
  TranslationConfiguration -> ModuleMap -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann, Int, [Lean.Type])
translateGoalAsDeclImportsWithTelescope configuration mm name@(Lean.Ident nameStr) t tp = do
  (doc, arity, binderTys) <-
    TermTranslation.translateDefDocWithTelescope configuration mm name t tp
  let stub =
        pretty ("theorem " <> nameStr <> "_holds : " <> nameStr <> " := by") <>
        hardline <> pretty ("  sorry" :: String)
  -- @doc@ already ends with a trailing hardline from @prettyDecl@; the
  -- vcat separator adds one more for the blank line before @stub@, so
  -- no additional leading hardline is needed on the stub.
  pure
    ( vcat
        [ preamble True configuration
        , hardline <> doc
        , stub
        ]
    , arity
    , binderTys )

-- | Translate a Cryptol module to a Lean namespace block. Wraps the
-- translated defs in @namespace nm … end nm@ so Cryptol users
-- reference translated functions via @nm.f@. Mirrors
-- 'SAWCoreRocq.Rocq.translateCryptolModule'.
translateCryptolModule ::
  SharedContext -> CryptolEnv ->
  Lean.Ident -> -- ^ namespace name (typically the .cry file's base name)
  TranslationConfiguration ->
  (Term -> IO Term) ->
    -- ^ normalisation callback applied to each Cryptol term and its
    --   type before translation. Under specialization this unfolds
    --   the SAWCore Prelude; pass @pure@ for identity.
  [Lean.Ident] ->
    -- ^ globals already translated (e.g. names from a previously-
    --   emitted SAWCorePrelude) so we don't re-emit their bodies.
  CryptolModule ->
  IO (Either TranslationError (Doc ann))
translateCryptolModule sc env nm configuration normalize globalDecls m = do
  translated <-
    CMT.translateCryptolModule sc env configuration normalize globalDecls m
  pure $ Lean.prettyDecl . Lean.Namespace (escapeIdent nm) <$> translated

-- | Extract the short 'String' name of a SAWCore 'ModuleDecl', if any.
-- Used by 'saw-central' to build the skip-list of already-translated
-- globals when running the translator over a Cryptol module.
moduleDeclName :: ModuleDecl -> Maybe String
moduleDeclName (TypeDecl (DataType { dtName }))      = Just (Text.unpack (toShortName (nameInfo dtName)))
moduleDeclName (DefDecl  (Def     { defName }))      = Just (Text.unpack (toShortName (nameInfo defName)))
moduleDeclName InjectCodeDecl{}                      = Nothing

-- | Walk a SAWCore 'Module', emitting each 'ModuleDecl' as a Lean
-- declaration document. Wraps the result in a Lean @namespace@
-- block named after the (translated) source module. Mirrors
-- 'SAWCoreRocq.Rocq.translateSAWModule'.
translateSAWModule ::
  SharedContext -> TranslationConfiguration -> ModuleMap -> Module ->
  IO (Doc ann)
translateSAWModule sc configuration mm m = do
  let srcName  = moduleName m
      lnName   = translateModuleName srcName
      nsHeader = "namespace" <+> prettyModuleName lnName
      nsFooter = "end" <+> prettyModuleName lnName
  decls' <- mapM
    (SAWModuleTranslation.translateDecl sc configuration (Just srcName) mm)
    (moduleDecls m)
  pure $ vsep $ [nsHeader, ""] ++ decls' ++ [nsFooter, ""]
  where
    prettyModuleName :: ModuleName -> Doc ann
    prettyModuleName mn = pretty (Text.intercalate "." (moduleNamePieces mn))
