{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : SAWCoreLean.Lean
Copyright   : Galois, Inc. 2026
License     : BSD3
Maintainer  : saw@galois.com
Stability   : experimental
Portability : portable

Top-level entry points for the SAWCore-to-Lean translator. Mirrors
"SAWCoreRocq.Rocq" (preamble / @translateTermAsDeclImports@) but with
a minimal preamble suited to Lean's import syntax.
-}

module SAWCoreLean.Lean
  ( TranslationConfiguration(..)
  , preamble
  , translateTermAsDeclImports
  , translateGoalAsDeclImports
  , translateSAWModule
  , moduleDeclName
  , ppTranslationError
  ) where

import qualified Data.Text                as Text
import           Prettyprinter

import qualified Language.Lean.AST        as Lean
import           SAWCore.Module           (Def(..), Module, ModuleDecl(..),
                                           ModuleMap, DataType(..),
                                           moduleName, moduleDecls)
import           SAWCore.Name             (nameInfo, moduleNameText, toShortName)
import           SAWCore.SharedTerm

import qualified SAWCoreLean.SAWModule    as SAWModuleTranslation
import           SAWCoreLean.Monad
import           SAWCoreLean.SpecialTreatment (translateModuleName)
import qualified SAWCoreLean.Term         as TermTranslation

-- | Imports emitted at the top of every generated file.
--
-- The @CryptolToLean@ root module (under @saw-core-lean/lean/@)
-- re-exports the handwritten support modules. The translator always
-- emits fully-qualified names, so no per-module @open@ is needed to
-- make identifiers resolve. Phase 2's generated preludes add more
-- re-exports here.
preamble :: TranslationConfiguration -> Doc ann
preamble _configuration = vsep
  [ "/- Mandatory imports from saw-core-lean -/"
  , "import CryptolToLean"
  , ""
  , "/- Code generated by saw-core-lean -/"
  ]

-- | Translate a single SAWCore 'Term' (with its type) to a Lean @def@
-- with the given name, prepended by the standard preamble.
translateTermAsDeclImports ::
  TranslationConfiguration -> ModuleMap -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann)
translateTermAsDeclImports configuration mm name t tp = do
  doc <- TermTranslation.translateDefDoc configuration mm name t tp
  pure (vcat [preamble configuration, hardline <> doc])

-- | Translate a SAWCore proof goal (a 'Term' of type @Prop@) to a
-- Lean file containing two declarations: a @def@ naming the
-- proposition, and a @theorem <name>_holds : <name> := by sorry@
-- stub the user discharges by hand. Mirrors the design-doc §3.2
-- shape of 'offline_lean' output.
translateGoalAsDeclImports ::
  TranslationConfiguration -> ModuleMap -> Lean.Ident -> Term -> Term ->
  Either TranslationError (Doc ann)
translateGoalAsDeclImports configuration mm name@(Lean.Ident nameStr) t tp = do
  doc <- TermTranslation.translateDefDoc configuration mm name t tp
  let stub =
        pretty ("theorem " <> nameStr <> "_holds : " <> nameStr <> " := by") <>
        hardline <> pretty ("  sorry" :: String)
  -- @doc@ already ends with a trailing hardline from @prettyDecl@; the
  -- vcat separator adds one more for the blank line before @stub@, so
  -- no additional leading hardline is needed on the stub.
  pure $ vcat
    [ preamble configuration
    , hardline <> doc
    , stub
    ]

-- | Translate an entire SAWCore 'Module' to a Lean file: wraps the
-- module's declarations in @namespace X … end X@ where @X@ is the
-- translated module name. Mirrors 'SAWCoreRocq.Rocq.translateSAWModule'.
translateSAWModule ::
  SharedContext -> TranslationConfiguration -> ModuleMap -> Module ->
  IO (Doc ann)
translateSAWModule sc configuration mm m = do
  let name = translateModuleName (moduleName m)
      nameDoc = pretty (moduleNameText name)
  decls <- mapM (SAWModuleTranslation.translateDecl sc configuration
                  (Just (moduleName m)) mm) (moduleDecls m)
  let header = "namespace" <+> nameDoc
      footer = "end" <+> nameDoc
  pure $ vsep $ [header, mempty] ++ decls ++ [footer, mempty]

-- | Extract the short 'String' name of a SAWCore 'ModuleDecl', if any.
-- Used by 'saw-central' to build the skip-list of already-translated
-- globals when running the translator over a Cryptol module.
moduleDeclName :: ModuleDecl -> Maybe String
moduleDeclName (TypeDecl (DataType { dtName }))      = Just (Text.unpack (toShortName (nameInfo dtName)))
moduleDeclName (DefDecl  (Def     { defName }))      = Just (Text.unpack (toShortName (nameInfo defName)))
moduleDeclName InjectCodeDecl{}                      = Nothing
