/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean, then completed by a user proof. -/

noncomputable def goal : Prop :=
  (x : Vec 8 Bool) -> (y : Vec 8 Bool) -> let x := (Pure.pure x);
  let y := (Pure.pure y); @Eq (Except String Bool)
  (CryptolToLean.SAWCorePreludeExtra.iteM Bool (Bind.bind x
  (fun v_1 => Bind.bind y (fun v_2 => Pure.pure (bvEq 8 v_1 v_2)))) (Bind.bind
  (Bind.bind x (fun v_1 => Bind.bind y (fun v_2 => Pure.pure (bvAdd 8 v_1
  v_2)))) (fun v_1' => Bind.bind (Bind.bind x (fun v_1 => Bind.bind x
  (fun v_2 => Pure.pure (bvAdd 8 v_1 v_2)))) (fun v_2' => Pure.pure (bvEq 8 v_1'
  v_2')))) (Pure.pure Bool.true)) (Pure.pure Bool.true)

theorem goal_holds : goal := by
  intro x y
  by_cases hxy : bvEq 8 x y = true
  · have hEq : x = y := bvEq_eq_true_imp_eq 8 x y hxy
    subst y
    simp [CryptolToLean.SAWCorePreludeExtra.iteM, bvEq_refl, Pure.pure,
      Bind.bind, Except.pure, Except.bind]
  · have hfalse : bvEq 8 x y = false := by
      cases h : bvEq 8 x y
      · rfl
      · exfalso
        exact hxy h
    simp [CryptolToLean.SAWCorePreludeExtra.iteM, hfalse, Pure.pure,
      Bind.bind, Except.pure, Except.bind]
