[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "saw-lexer"
version = "0.0.1"
dependencies = ["pygments"]

[project.entry-points."pygments.lexers"]
saw_lexer = "saw_lexer:SAWScriptLexer"
