/-
ChaCha20 core-round quarterround verify (obligation qround_d1_LLVM_points-to0,
state positions 1,6,11,12) — completed outline, ACCEPTED
under the `native-eval` trust tier (2026-07-21 user decision; see
.trust-tier).

One of the EIGHT qround obligations emitted by
workflows/llvm_chacha20_core_verify (four column rounds, four diagonal
rounds); same quarterround equation as proofs/llvm_chacha20_q_eq at a
different position tuple. The generated `def goal` embeds vacuous
bounds-proof fallbacks whose dead admit-placeholder tails are stripped
here (proof irrelevance keeps `goal` rfl-equal to the generated
goal; the harness drift check enforces that), and `goal_holds` is
discharged: rowround-recipe scaffold with the rotate bridge at the
ChaCha20 rotation amounts {16,12,8,7}; the 12 unchanged positions
close by bvEq_refl, the 4 quarterround positions by `bv_decide`.

TRUST TIER NOTE — RESOLVE LATER: `bv_decide` proofs depend on
per-invocation proof-local native axioms
(`goal_holds._native.bv_decide.ax_*`); see the two-tier policy in
saw-core-lean/doc/proof-cookbook.md. RESOLUTION TRIGGER (recorded in
TODO.md): when lean-smt's cvc5 BV proof reconstruction lands upstream,
swap `bv_decide` -> `smt` and delete .trust-tier.
-/
/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean -/

noncomputable def goal : Prop :=
  (state : Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)) ->
  let state := (Pure.pure state); @Eq.{1} (Except String Bool) (foldrM Bool Bool
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (fun (b1 : Except String
  Bool) (b2 : Except String Bool) => CryptolToLean.SAWCorePreludeExtra.iteM Bool
  b1 b2 (Pure.pure Bool.false)) (Pure.pure Bool.true) (genWithBoundsM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) Bool
  (fun (i : Nat) (h_gen_bounds_ : LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) => let x__ := (let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  CryptolToLean.SAWCorePrimitives.zero_macro h_bounds_);
  let x__' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro) h_bounds_);
  let x__'' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_);
  let x__''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__'''' := (Bind.bind (Bind.bind x__' (fun v_1 => Bind.bind x__''
  (fun v_2 => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_1' => Bind.bind x__''' (fun v_2' => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2'))));
  let x__''''' := (Bind.bind (Bind.bind x__'''' (fun v_1 => Pure.pure (bvShl
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))))) (fun v_1' => Bind.bind
  (Bind.bind x__'''' (fun v_1 => Pure.pure (bvShr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))))) (fun v_2 => Pure.pure (bvOr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2))));
  let x__'''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__''''''' := (Bind.bind (Bind.bind x__''''' (fun v_1 => Bind.bind
  x__'''''' (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_1' => Bind.bind x__'' (fun v_2' => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2'))));
  let x__'''''''' := (Bind.bind (Bind.bind x__''''''' (fun v_1 => Pure.pure
  (bvShl (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))))) (fun v_1' => Bind.bind
  (Bind.bind x__''''''' (fun v_1 => Pure.pure (bvShr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))))) (fun v_2 => Pure.pure (bvOr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2))));
  let x__''''''''' := (Bind.bind (Bind.bind x__'''''''' (fun v_1 => Bind.bind
  x__' (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_1' => Bind.bind x__'' (fun v_2' => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2'))));
  let x__'''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_);
  let x__''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_);
  let x__'''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_);
  let x__''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_);
  let x__'''''''''''''' := (Bind.bind x__''''' (fun v_1 => Bind.bind
  x__''''''''' (fun v_2 => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))));
  let x__''''''''''''''' := (Bind.bind (Bind.bind x__''''''''''''''
  (fun v_1 => Pure.pure (bvShl (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))))) (fun v_1' => Bind.bind
  (Bind.bind x__'''''''''''''' (fun v_1 => Pure.pure (bvShr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))))) (fun v_2 => Pure.pure (bvOr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2))));
  let x__'''''''''''''''' := (Bind.bind (Bind.bind x__'''''
  (fun v_1 => Bind.bind x__''''''''''''''' (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_1' => Bind.bind x__'''''' (fun v_2' => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2'))));
  let x__''''''''''''''''' := (Bind.bind x__'''''''' (fun v_1 => Bind.bind
  x__'''''''''''''''' (fun v_2 => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))));
  let x__'''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_);
  let x__''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__'''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__''''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__'''''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__''''''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__'''''''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) state
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) h_bounds_);
  let x__''''''''''''''''''''''''' := (vecSequenceM 4 (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  #v[x__', x__'', x__'''''', x__''']);
  let x__'''''''''''''''''''''''''' := (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''' (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro) h_bounds_);
  let x__''''''''''''''''''''''''''' := (Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''' CryptolToLean.SAWCorePrimitives.zero_macro
  h_bounds_) (fun v_1 => Bind.bind x__''''''''''''''''''''''''''
  (fun v_2 => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))));
  let x__'''''''''''''''''''''''''''' := (Bind.bind (Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''' (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_) (fun v_1 => Bind.bind
  x__''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_2' => Pure.pure (rotateL (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool v_2'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))))));
  let x__''''''''''''''''''''''''''''' := (Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''' (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_) (fun v_1 => Bind.bind
  x__'''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))));
  let x__'''''''''''''''''''''''''''''' := (Bind.bind (Bind.bind
  x__'''''''''''''''''''''''''' (fun v_1 => Bind.bind
  x__''''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_2' => Pure.pure (rotateL (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool v_2'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))));
  let x__''''''''''''''''''''''''''''''' := (Bind.bind
  x__''''''''''''''''''''''''''' (fun v_1 => Bind.bind
  x__'''''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))));
  let x__'''''''''''''''''''''''''''''''' := (Bind.bind (Bind.bind
  x__'''''''''''''''''''''''''''' (fun v_1 => Bind.bind
  x__''''''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_2' => Pure.pure (rotateL (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool v_2'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))));
  let x__''''''''''''''''''''''''''''''''' := (Bind.bind
  x__''''''''''''''''''''''''''''' (fun v_1 => Bind.bind
  x__'''''''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))));
  let x__'''''''''''''''''''''''''''''''''' := (vecSequenceM 4 (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  #v[x__''''''''''''''''''''''''''''''', Bind.bind (Bind.bind
  x__'''''''''''''''''''''''''''''' (fun v_1 => Bind.bind
  x__''''''''''''''''''''''''''''''''' (fun v_2 => Pure.pure (bvXor
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_2' => Pure.pure (rotateL (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool v_2'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))), x__''''''''''''''''''''''''''''''''', x__'''''''''''''''''''''''''''''''']);
  Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (vecSequenceM 16 (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  #v[x__, x__''''''''', x__'''''''''', x__''''''''''', x__'''''''''''', x__''''''''''''', Bind.bind
  (Bind.bind x__''''''''''''''''' (fun v_1 => Pure.pure (bvShl
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) (fun v_1' => Bind.bind
  (Bind.bind x__''''''''''''''''' (fun v_1 => Pure.pure (bvShr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))))) (fun v_2 => Pure.pure (bvOr
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1'
  v_2))), x__'''''''''''''''''', x__''''''''''''''''''', x__'''''''''''''''''''', x__''''''''''''''''''''', x__'''''''''''''''', x__''''''''''''''', x__'''''''''''''''''''''', x__''''''''''''''''''''''', x__''''''''''''''''''''''''])
  i h_bounds_) (fun v_1'' => Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (vecSequenceM 16 (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  #v[x__, let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''''''''''''
  CryptolToLean.SAWCorePrimitives.zero_macro
  h_bounds_, x__'''''''''', x__''''''''''', x__'''''''''''', x__''''''''''''', let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''''''''''''
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  h_bounds_, x__'''''''''''''''''', x__''''''''''''''''''', x__'''''''''''''''''''', x__''''''''''''''''''''', let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''''''''''''
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  h_bounds_, let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  x__''''''''''''''''''''''''''''''''''
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  h_bounds_, x__'''''''''''''''''''''', x__''''''''''''''''''''''', x__''''''''''''''''''''''''])
  i h_bounds_) (fun v_2' => Pure.pure (bvEq
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1'' v_2')))))) (Pure.pure
  Bool.true)

open CryptolToLean.SAWCorePrimitives CryptolToLean.SAWCoreVectors
  CryptolToLean.SAWCoreBitvectorsProofs CryptolToLean.SAWCorePreludeProofs

/-- The IN-ITP override at rotate granularity: the C shift-or
    decomposition of a 32-bit left-rotate equals the Cryptol `rotateL`.
    Same bridge as the salsa20 rowround/columnround rows, at the
    ChaCha20 rotation amounts. -/
theorem rotl_shlor_32 (x : Vec 32 Bool) (k : Nat) (hk : k < 32) :
    bvOr 32 (bvShl 32 x k) (bvShr 32 x (32 - k)) = rotateL 32 Bool x k := by
  have h : vecToBitVec (bvOr 32 (bvShl 32 x k) (bvShr 32 x (32 - k)))
         = vecToBitVec (rotateL 32 Bool x k) := by
    rw [vecToBitVec_bvOr, vecToBitVec_bvShl, vecToBitVec_bvShr, vecToBitVec_rotateL,
        BitVec.rotateLeft_def, Nat.mod_eq_of_lt hk]
  calc bvOr 32 (bvShl 32 x k) (bvShr 32 x (32 - k))
      = bitVecToVec (vecToBitVec (bvOr 32 (bvShl 32 x k) (bvShr 32 x (32-k)))) :=
        (bitVecToVec_vecToBitVec _).symm
    _ = bitVecToVec (vecToBitVec (rotateL 32 Bool x k)) := by rw [h]
    _ = rotateL 32 Bool x k := bitVecToVec_vecToBitVec _

theorem rotl_16 (x : Vec 32 Bool) : bvOr 32 (bvShl 32 x 16) (bvShr 32 x 16) = rotateL 32 Bool x 16 := rotl_shlor_32 x 16 (by decide)
theorem rotl_12 (x : Vec 32 Bool) : bvOr 32 (bvShl 32 x 12) (bvShr 32 x 20) = rotateL 32 Bool x 12 := rotl_shlor_32 x 12 (by decide)
theorem rotl_8  (x : Vec 32 Bool) : bvOr 32 (bvShl 32 x 8)  (bvShr 32 x 24) = rotateL 32 Bool x 8  := rotl_shlor_32 x 8  (by decide)
theorem rotl_7  (x : Vec 32 Bool) : bvOr 32 (bvShl 32 x 7)  (bvShr 32 x 25) = rotateL 32 Bool x 7  := rotl_shlor_32 x 7  (by decide)

/-- Abstract eager-sequence reduction: a literal vector of successes
    sequences to the pure vector. Proved once over opaque elements so
    the main discharge applies it as a single rewrite to the huge
    emitted words (not by inline monadic peeling). -/
theorem vecSeqM_map_ok {α n} (w : Vec n α) :
    vecSequenceM n α (Vector.map Except.ok w) = Except.ok w := by
  apply vecSequenceM_ok_of_get; intro i; simp

theorem seq4 (e0 e1 e2 e3 : Vec 32 Bool) :
    vecSequenceM 4 (Vec 32 Bool) #v[Except.ok e0, Except.ok e1, Except.ok e2, Except.ok e3] = Except.ok #v[e0, e1, e2, e3] := by
  rw [show (#v[Except.ok e0, Except.ok e1, Except.ok e2, Except.ok e3] : Vec 4 (Except String (Vec 32 Bool)))
        = Vector.map Except.ok #v[e0, e1, e2, e3] from by simp, vecSeqM_map_ok]

theorem seq16 (e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13 e14 e15 : Vec 32 Bool) :
    vecSequenceM 16 (Vec 32 Bool) #v[Except.ok e0, Except.ok e1, Except.ok e2, Except.ok e3, Except.ok e4, Except.ok e5, Except.ok e6, Except.ok e7, Except.ok e8, Except.ok e9, Except.ok e10, Except.ok e11, Except.ok e12, Except.ok e13, Except.ok e14, Except.ok e15] = Except.ok #v[e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15] := by
  rw [show (#v[Except.ok e0, Except.ok e1, Except.ok e2, Except.ok e3, Except.ok e4, Except.ok e5, Except.ok e6, Except.ok e7, Except.ok e8, Except.ok e9, Except.ok e10, Except.ok e11, Except.ok e12, Except.ok e13, Except.ok e14, Except.ok e15] : Vec 16 (Except String (Vec 32 Bool)))
        = Vector.map Except.ok #v[e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15] from by simp, vecSeqM_map_ok]

theorem foldr_ofFn_true (n : Nat) :
    Vector.foldr (fun a acc => Bool.rec (Except.ok (ε := String) false) acc a) (Except.ok true)
      (Vector.ofFn (fun _ : Fin n => true)) = Except.ok true := by
  induction n with
  | zero => rfl
  | succ k ih =>
    have hsplit : (Vector.ofFn (fun _ : Fin (k+1) => true))
                = (Vector.ofFn (fun _ : Fin k => true)).push true := by
      apply Vector.ext; intro i hi
      simp only [Vector.getElem_ofFn]
      by_cases hk : i < k
      · simp [Vector.getElem_push_lt hk]
      · have : i = k := by omega
        subst this; simp
    rw [hsplit, Vector.foldr_push]; exact ih

theorem foldr_ofFn_all_true {n : Nat} (g : Fin n → Bool) (h : ∀ i, g i = true) :
    Vector.foldr (fun a acc => Bool.rec (Except.ok (ε := String) false) acc a) (Except.ok true)
      (Vector.ofFn g) = Except.ok true := by
  have hg : Vector.ofFn g = Vector.ofFn (fun _ : Fin n => true) := by
    apply Vector.ext; intro i hi; simp only [Vector.getElem_ofFn]; exact h ⟨i, hi⟩
  rw [hg, foldr_ofFn_true]

set_option maxRecDepth 100000 in
theorem goal_holds : goal := by
  intro state
  simp only [goal, Pure.pure, Bind.bind, Except.pure, Except.bind,
    natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro,
    Nat.reduceMul, Nat.reduceAdd, Nat.reduceSub,
    seq4, seq16, atWithProof_checkedM, genWithBoundsM,
    rotl_16, rotl_12, rotl_8, rotl_7,
    foldrM, ofFnM_except_ok, bvEq_refl, CryptolToLean.SAWCorePreludeExtra.iteM,
    Vector.getElem_mk, List.getElem_toArray, List.getElem_cons_succ, List.getElem_cons_zero]
  apply foldr_ofFn_all_true
  simp only [Fin.forall_fin_succ, Fin.forall_fin_zero, and_true]
  refine ⟨?_,?_,?_,?_,?_,?_,?_,?_,?_,?_,?_,?_,?_,?_,?_,?_⟩
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    unfold bvEq
    refine decide_eq_true ?_
    simp only [vecToBitVec_bvXor, vecToBitVec_bvAdd, vecToBitVec_rotateL]
    bv_decide
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    unfold bvEq
    refine decide_eq_true ?_
    simp only [vecToBitVec_bvXor, vecToBitVec_bvAdd, vecToBitVec_rotateL]
    bv_decide
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    unfold bvEq
    refine decide_eq_true ?_
    simp only [vecToBitVec_bvXor, vecToBitVec_bvAdd, vecToBitVec_rotateL]
    bv_decide
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    unfold bvEq
    refine decide_eq_true ?_
    simp only [vecToBitVec_bvXor, vecToBitVec_bvAdd, vecToBitVec_rotateL]
    bv_decide
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
  · simp only [Fin.val_zero, Fin.val_succ, Vector.getElem_mk, List.getElem_toArray,
      List.getElem_cons_succ, List.getElem_cons_zero]
    exact bvEq_refl _ _
