/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean -/

/-
W2 OPENER DISCHARGE - byte-decomposed 4-byte carry-chain addition vs
bvAdd 32 (llvm_byte_add_verify act 3, mp_add_simple == a + b).

Completed outline of the generated goal, drift-checked definitionally
against the tracked artifact. The emitted term is a 16-fold bvAdd /
bvSShr / bvShl / bvOr pipeline over zero-padded byte windows; the
outline names each repeated monadic shape in BADischarge (definitionally
the emitted subterms - the vacuous bounds fallbacks are replaced by
direct omega proofs, and the reducible numeral macro chains by their
literals; both moves are kernel-defeq).
-/

namespace BADischarge

/-- T-length prefix re-gen of a wrapped 32-bit vector: the emitted
`gen T (fun k => at 32 X k)` truncation tower. -/
noncomputable def pfxM (T : Nat) (hT : T ≤ 32)
    (X : Except String (Vec 32 Bool)) : Except String (Vec T Bool) :=
  genWithBoundsM T Bool (fun k hk =>
    atWithProof_checkedM 32 Bool X k (by omega))

/-- 8-bit window at offset K through a T-length prefix of X, read at
result position i (only used at i in [24,32); the emitted shape indexes
the window at `subNat i 24`). -/
noncomputable def winM (T K : Nat) (hT : T ≤ 32) (hK : K + 8 ≤ T)
    (X : Except String (Vec 32 Bool)) (i : Nat) (hi : i < 32) :
    Except String Bool :=
  atWithProof_checkedM 8 Bool
    (genWithBoundsM 8 Bool (fun j hj =>
      atWithProof_checkedM T Bool (pfxM T hT X) (addNat K j)
        (by show K + j < T; omega)))
    (subNat i 24) (by show i - 24 < 8; omega)

/-- Zero-extend-to-32 of the byte at Vec offset K (MSB-first): the
emitted `gen 32 (fun i => ite (i < 24) 0-pad (byte window))` tower. -/
noncomputable def zbM (T K : Nat) (hT : T ≤ 32) (hK : K + 8 ≤ T)
    (X : Except String (Vec 32 Bool)) : Except String (Vec 32 Bool) :=
  genWithBoundsM 32 Bool (fun i hi =>
    CryptolToLean.SAWCorePreludeExtra.iteM Bool (Pure.pure (ltNat i 24))
      (atRuntimeCheckedM 24 Bool (Pure.pure (bvNat 24 0)) i)
      (winM T K hT hK X i hi))

/-- Per-byte sum of the two inputs: `zext8_32(a byte K) + zext8_32(b byte K)`. -/
noncomputable def sumM (T K : Nat) (hT : T ≤ 32) (hK : K + 8 ≤ T)
    (a b : Except String (Vec 32 Bool)) : Except String (Vec 32 Bool) :=
  Bind.bind (zbM T K hT hK a) (fun v_1 =>
    Bind.bind (zbM T K hT hK b) (fun v_2 =>
      Pure.pure (bvAdd 32 v_1 v_2)))

/-- Low-16 mask of a wrapped 32-bit value: the emitted
`gen 32 (fun i => ite (i < 16) 0-pad X[i])` tower (truncate-to-16 then
zero-extend back, fused). -/
noncomputable def low16M (X : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  genWithBoundsM 32 Bool (fun i hi =>
    CryptolToLean.SAWCorePreludeExtra.iteM Bool (Pure.pure (ltNat i 16))
      (atRuntimeCheckedM 16 Bool (Pure.pure (bvNat 16 0)) i)
      (atWithProof_checkedM 16 Bool
        (genWithBoundsM 16 Bool (fun j hj =>
          atWithProof_checkedM 32 Bool (pfxM 32 (by omega) X) (addNat 16 j)
            (by show 16 + j < 32; omega)))
        (subNat i 16) (by show i - 16 < 16; omega)))

/-- Carry extraction: arithmetic-shift the low-16 partial sum right by 8. -/
noncomputable def carryM (X : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  Bind.bind (low16M X) (fun v_1' => Pure.pure (bvSShr 31 v_1' 8))

/-- Partial sums s0..s3 of the carry chain. -/
noncomputable def s0M (a b : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  sumM 32 24 (by omega) (by omega) a b

noncomputable def s1M (a b : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  Bind.bind (sumM 24 16 (by omega) (by omega) a b) (fun v_1'' =>
    Bind.bind (carryM (s0M a b)) (fun v_2' =>
      Pure.pure (bvAdd 32 v_1'' v_2')))

noncomputable def s2M (a b : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  Bind.bind (sumM 16 8 (by omega) (by omega) a b) (fun v_1'''' =>
    Bind.bind (carryM (s1M a b)) (fun v_2'' =>
      Pure.pure (bvAdd 32 v_1'''' v_2'')))

noncomputable def s3M (a b : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  Bind.bind (sumM 8 0 (by omega) (by omega) a b) (fun v_1'''''' =>
    Bind.bind (carryM (s2M a b)) (fun v_2''' =>
      Pure.pure (bvAdd 32 v_1'''''' v_2''')))

/-- The 24-bit middle vector of the fused r1:r0 reassembly: zeros below
16, byte 24..31 of X at positions 16..23. -/
noncomputable def mid24M (X : Except String (Vec 32 Bool)) :
    Except String (Vec 24 Bool) :=
  genWithBoundsM 24 Bool (fun i hi =>
    CryptolToLean.SAWCorePreludeExtra.iteM Bool (Pure.pure (ltNat i 16))
      (atRuntimeCheckedM 16 Bool (Pure.pure (bvNat 16 0)) i)
      (atWithProof_checkedM 8 Bool
        (genWithBoundsM 8 Bool (fun j hj =>
          atWithProof_checkedM 32 Bool (pfxM 32 (by omega) X) (addNat 24 j)
            (by show 24 + j < 32; omega)))
        (subNat i 16) (by show i - 16 < 8; omega)))

/-- The fused r1:r0 32-bit reassembly vector (positions 0..15 zero,
16..23 = byte of s1, 24..31 = byte of s0). -/
noncomputable def gAM (a b : Except String (Vec 32 Bool)) :
    Except String (Vec 32 Bool) :=
  genWithBoundsM 32 Bool (fun i hi =>
    CryptolToLean.SAWCorePreludeExtra.iteM Bool (Pure.pure (ltNat i 24))
      (atRuntimeCheckedM 24 Bool (mid24M (s1M a b)) i)
      (winM 32 24 (by omega) (by omega) (s0M a b) i hi))

/-! ### Pure characterizations (Phase 1)

Each emitted monadic tower applied to `Except.ok` inputs is
`Except.ok` of a pure `Vector.ofFn` slice value. The slice values are
stated in the `if`-guarded `atWithDefault` form the W2 library lemmas
(`vecToBitVec_zeroPadWindow32` / `vecToBitVec_bytePack32`) carry into
`BitVec` shift/mask images. -/

/-- Pure image of `zbM`: zero-extend-to-32 of the byte at Vec offset K. -/
noncomputable def zbyte (v : Vec 32 Bool) (K : Nat) : Vec 32 Bool :=
  Vector.ofFn (fun i : Fin 32 =>
    if i.val < 24 then false
    else atWithDefault 32 Bool false v (K + (i.val - 24)))

/-- Pure image of `low16M`: keep the low 16 value bits (positions
16..31 MSB-first), zero the rest. -/
noncomputable def low16 (s : Vec 32 Bool) : Vec 32 Bool :=
  Vector.ofFn (fun i : Fin 32 =>
    if i.val < 16 then false
    else atWithDefault 32 Bool false s (16 + (i.val - 16)))

/-- Pure image of `carryM`. -/
noncomputable def carry (s : Vec 32 Bool) : Vec 32 Bool :=
  bvSShr 31 (low16 s) 8

/-- Pure partial sums of the carry chain. -/
noncomputable def s0v (a b : Vec 32 Bool) : Vec 32 Bool :=
  bvAdd 32 (zbyte a 24) (zbyte b 24)
noncomputable def s1v (a b : Vec 32 Bool) : Vec 32 Bool :=
  bvAdd 32 (bvAdd 32 (zbyte a 16) (zbyte b 16)) (carry (s0v a b))
noncomputable def s2v (a b : Vec 32 Bool) : Vec 32 Bool :=
  bvAdd 32 (bvAdd 32 (zbyte a 8) (zbyte b 8)) (carry (s1v a b))
noncomputable def s3v (a b : Vec 32 Bool) : Vec 32 Bool :=
  bvAdd 32 (bvAdd 32 (zbyte a 0) (zbyte b 0)) (carry (s2v a b))

/-- Pure image of `gAM`: the fused r1:r0 reassembly. -/
noncomputable def packA (s1 s0 : Vec 32 Bool) : Vec 32 Bool :=
  Vector.ofFn (fun i : Fin 32 =>
    if i.val < 24 then
      (if i.val < 16 then false
       else atWithDefault 32 Bool false s1 (24 + (i.val - 16)))
    else atWithDefault 32 Bool false s0 (24 + (i.val - 24)))

theorem pfx_elem_ok (x : Vec 32 Bool) (k : Nat) (h : k < 32) :
    atWithProof_checkedM 32 Bool (Except.ok x) k h = Except.ok (x[k]'h) :=
  rfl

theorem winM_ok (T K : Nat) (hT : T ≤ 32) (hK : K + 8 ≤ T)
    (x : Vec 32 Bool) (i : Nat) (hi : i < 32) :
    winM T K hT hK (Except.ok x) i hi
      = Except.ok (atWithDefault 32 Bool false x (K + (i - 24))) := by
  unfold winM pfxM
  refine Eq.trans (atWithProof_gen_ok _
      (fun j (hj : j < 8) => x[K + j]'(by omega)) (subNat i 24)
      (by show i - 24 < 8; omega) ?_) ?_
  · intro j hj
    refine Eq.trans (atWithProof_gen_ok _
        (fun k (hk : k < T) => x[k]'(by omega)) (addNat K j)
        (by show K + j < T; omega) ?_) ?_
    · intro k hk
      rfl
    · rfl
  · rw [CryptolToLean.SAWCorePreludeProofs.atWithDefault_lt _ _ _
        (show K + (i - 24) < 32 by omega)]
    rfl

theorem zbM_ok (T K : Nat) (hT : T ≤ 32) (hK : K + 8 ≤ T)
    (x : Vec 32 Bool) :
    zbM T K hT hK (Except.ok x) = Except.ok (zbyte x K) := by
  unfold zbM zbyte
  refine genWithBoundsM_eq_ok _
    (fun i (hi : i < 32) =>
      if i < 24 then false
      else atWithDefault 32 Bool false x (K + (i - 24))) ?_
  intro i hi
  show _ = Except.ok (if i < 24 then false
    else atWithDefault 32 Bool false x (K + (i - 24)))
  by_cases h : i < 24
  · have hlt : ltNat i 24 = true := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_true,
        show (Pure.pure (bvNat 24 0) : Except String (Vec 24 Bool))
          = Except.ok (bvNat 24 0) from rfl,
        atRuntimeCheckedM_ok_lt 24 (bvNat 24 0) i h,
        getElem_bvNat_zero 24 i h, if_pos h]
  · have hlt : ltNat i 24 = false := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_false, winM_ok T K hT hK x i hi, if_neg h]

theorem sumM_ok (T K : Nat) (hT : T ≤ 32) (hK : K + 8 ≤ T)
    (a b : Vec 32 Bool) :
    sumM T K hT hK (Except.ok a) (Except.ok b)
      = Except.ok (bvAdd 32 (zbyte a K) (zbyte b K)) := by
  unfold sumM
  rw [zbM_ok, zbM_ok]
  rfl

theorem low16M_ok (X : Except String (Vec 32 Bool)) (x : Vec 32 Bool)
    (hX : X = Except.ok x) :
    low16M X = Except.ok (low16 x) := by
  subst hX
  unfold low16M low16 pfxM
  refine genWithBoundsM_eq_ok _
    (fun i (hi : i < 32) =>
      if i < 16 then false
      else atWithDefault 32 Bool false x (16 + (i - 16))) ?_
  intro i hi
  show _ = Except.ok (if i < 16 then false
    else atWithDefault 32 Bool false x (16 + (i - 16)))
  by_cases h : i < 16
  · have hlt : ltNat i 16 = true := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_true,
        show (Pure.pure (bvNat 16 0) : Except String (Vec 16 Bool))
          = Except.ok (bvNat 16 0) from rfl,
        atRuntimeCheckedM_ok_lt 16 (bvNat 16 0) i h,
        getElem_bvNat_zero 16 i h, if_pos h]
  · have hlt : ltNat i 16 = false := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_false]
    refine Eq.trans (atWithProof_gen_ok _
        (fun j (hj : j < 16) => x[16 + j]'(by omega)) (subNat i 16)
        (by show i - 16 < 16; omega) ?_) ?_
    · intro j hj
      refine Eq.trans (atWithProof_gen_ok _
          (fun k (hk : k < 32) => x[k]'hk) (addNat 16 j)
          (by show 16 + j < 32; omega) ?_) ?_
      · intro k hk
        rfl
      · rfl
    · rw [if_neg h,
          CryptolToLean.SAWCorePreludeProofs.atWithDefault_lt _ _ _
            (show 16 + (i - 16) < 32 by omega)]
      rfl

theorem carryM_ok (X : Except String (Vec 32 Bool)) (x : Vec 32 Bool)
    (hX : X = Except.ok x) :
    carryM X = Except.ok (carry x) := by
  unfold carryM carry
  rw [low16M_ok X x hX]
  rfl

theorem s0M_ok (a b : Vec 32 Bool) :
    s0M (Except.ok a) (Except.ok b) = Except.ok (s0v a b) := by
  unfold s0M s0v
  exact sumM_ok 32 24 (by omega) (by omega) a b

theorem s1M_ok (a b : Vec 32 Bool) :
    s1M (Except.ok a) (Except.ok b) = Except.ok (s1v a b) := by
  unfold s1M s1v
  rw [sumM_ok, carryM_ok _ _ (s0M_ok a b)]
  rfl

theorem s2M_ok (a b : Vec 32 Bool) :
    s2M (Except.ok a) (Except.ok b) = Except.ok (s2v a b) := by
  unfold s2M s2v
  rw [sumM_ok, carryM_ok _ _ (s1M_ok a b)]
  rfl

theorem s3M_ok (a b : Vec 32 Bool) :
    s3M (Except.ok a) (Except.ok b) = Except.ok (s3v a b) := by
  unfold s3M s3v
  rw [sumM_ok, carryM_ok _ _ (s2M_ok a b)]
  rfl

theorem mid24M_ok (X : Except String (Vec 32 Bool)) (x : Vec 32 Bool)
    (hX : X = Except.ok x) :
    mid24M X = Except.ok (Vector.ofFn (fun i : Fin 24 =>
      if i.val < 16 then false
      else atWithDefault 32 Bool false x (24 + (i.val - 16)))) := by
  subst hX
  unfold mid24M pfxM
  refine genWithBoundsM_eq_ok _
    (fun i (hi : i < 24) =>
      if i < 16 then false
      else atWithDefault 32 Bool false x (24 + (i - 16))) ?_
  intro i hi
  show _ = Except.ok (if i < 16 then false
    else atWithDefault 32 Bool false x (24 + (i - 16)))
  by_cases h : i < 16
  · have hlt : ltNat i 16 = true := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_true,
        show (Pure.pure (bvNat 16 0) : Except String (Vec 16 Bool))
          = Except.ok (bvNat 16 0) from rfl,
        atRuntimeCheckedM_ok_lt 16 (bvNat 16 0) i h,
        getElem_bvNat_zero 16 i h, if_pos h]
  · have hlt : ltNat i 16 = false := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_false]
    refine Eq.trans (atWithProof_gen_ok _
        (fun j (hj : j < 8) => x[24 + j]'(by omega)) (subNat i 16)
        (by show i - 16 < 8; omega) ?_) ?_
    · intro j hj
      refine Eq.trans (atWithProof_gen_ok _
          (fun k (hk : k < 32) => x[k]'hk) (addNat 24 j)
          (by show 24 + j < 32; omega) ?_) ?_
      · intro k hk
        rfl
      · rfl
    · rw [if_neg h,
          CryptolToLean.SAWCorePreludeProofs.atWithDefault_lt _ _ _
            (show 24 + (i - 16) < 32 by omega)]
      rfl

theorem gAM_ok (a b : Vec 32 Bool) :
    gAM (Except.ok a) (Except.ok b)
      = Except.ok (packA (s1v a b) (s0v a b)) := by
  unfold gAM packA
  refine genWithBoundsM_eq_ok _
    (fun i (hi : i < 32) =>
      if i < 24 then
        (if i < 16 then false
         else atWithDefault 32 Bool false (s1v a b) (24 + (i - 16)))
      else atWithDefault 32 Bool false (s0v a b) (24 + (i - 24))) ?_
  intro i hi
  show _ = Except.ok (if i < 24 then
      (if i < 16 then false
       else atWithDefault 32 Bool false (s1v a b) (24 + (i - 16)))
    else atWithDefault 32 Bool false (s0v a b) (24 + (i - 24)))
  by_cases h : i < 24
  · have hlt : ltNat i 24 = true := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_true, mid24M_ok _ _ (s1M_ok a b),
        atRuntimeCheckedM_ok_lt 24 _ i h, if_pos h,
        Vector.getElem_ofFn]
  · have hlt : ltNat i 24 = false := by simp [ltNat_eq_decide_lt, h]
    rw [hlt, iteM_pure_false, s0M_ok a b,
        winM_ok 32 24 (by omega) (by omega) (s0v a b) i hi, if_neg h]

/-! ### BitVec images (Phase 2)

The pure slice values move into `Lean.BitVec` shift/mask images via
the W2 library lemmas; `bvSShr` collapses to the logical shift because
the shifted operand is a 16-bit-masked value (sign bit clear). -/

theorem zbyte_img (v : Vec 32 Bool) (K : Nat) (hK : K ≤ 24) :
    vecToBitVec (zbyte v K)
      = (vecToBitVec v >>> (24 - K)) &&& 255#32 := by
  unfold zbyte
  rw [vecToBitVec_zeroPadWindow32 v 24 K (by omega) hK]

theorem low16_img (s : Vec 32 Bool) :
    vecToBitVec (low16 s) = vecToBitVec s &&& 65535#32 := by
  unfold low16
  rw [vecToBitVec_zeroPadWindow32 s 16 16 (by omega) (by omega)]
  rw [show (16 - 16 : Nat) = 0 from rfl, BitVec.ushiftRight_zero]

theorem packA_img (x1 x0 : Vec 32 Bool) :
    vecToBitVec (packA x1 x0)
      = ((vecToBitVec x1 &&& 255#32) <<< 8) ||| (vecToBitVec x0 &&& 255#32) := by
  unfold packA
  exact vecToBitVec_bytePack32 x1 x0

theorem carry_img (s : Vec 32 Bool) :
    vecToBitVec (carry s) = (vecToBitVec s &&& 65535#32) >>> 8 := by
  unfold carry
  rw [vecToBitVec_bvSShr, low16_img]
  refine BitVec.sshiftRight_eq_of_msb_false ?_
  rw [BitVec.msb_and]
  simp [show (65535#32).msb = false from by decide]

theorem s0v_img (a b : Vec 32 Bool) :
    vecToBitVec (s0v a b)
      = (vecToBitVec a &&& 255#32) + (vecToBitVec b &&& 255#32) := by
  unfold s0v
  rw [vecToBitVec_bvAdd, zbyte_img a 24 (by omega), zbyte_img b 24 (by omega)]
  simp only [show (24 - 24 : Nat) = 0 from rfl, BitVec.ushiftRight_zero]

theorem s1v_img (a b : Vec 32 Bool) :
    vecToBitVec (s1v a b)
      = ((vecToBitVec a >>> 8 &&& 255#32) + (vecToBitVec b >>> 8 &&& 255#32))
        + ((vecToBitVec (s0v a b) &&& 65535#32) >>> 8) := by
  unfold s1v
  rw [vecToBitVec_bvAdd, vecToBitVec_bvAdd,
      zbyte_img a 16 (by omega), zbyte_img b 16 (by omega), carry_img]

theorem s2v_img (a b : Vec 32 Bool) :
    vecToBitVec (s2v a b)
      = ((vecToBitVec a >>> 16 &&& 255#32) + (vecToBitVec b >>> 16 &&& 255#32))
        + ((vecToBitVec (s1v a b) &&& 65535#32) >>> 8) := by
  unfold s2v
  rw [vecToBitVec_bvAdd, vecToBitVec_bvAdd,
      zbyte_img a 8 (by omega), zbyte_img b 8 (by omega), carry_img]

theorem s3v_img (a b : Vec 32 Bool) :
    vecToBitVec (s3v a b)
      = ((vecToBitVec a >>> 24 &&& 255#32) + (vecToBitVec b >>> 24 &&& 255#32))
        + ((vecToBitVec (s2v a b) &&& 65535#32) >>> 8) := by
  unfold s3v
  rw [vecToBitVec_bvAdd, vecToBitVec_bvAdd,
      zbyte_img a 0 (by omega), zbyte_img b 0 (by omega), carry_img]

/-! ### Arithmetic core (Phase 3)

The whole equation moves to `Nat` via `toNat`, masks become `% 256` /
`% 65536`, the disjoint-range ORs become sums, and the closing omega
sees the 4-byte carry-chain identity over six abstracted variables
(the atoms MUST be generalized first: omega's preprocessing otherwise
defeq-compares the underlying noncomputable towers and blows the
heartbeat budget; and the divisions must be in chained-by-256 form —
omega does not identify `x / 65536` with `x / 256 / 256` on its own). -/

theorem final_eq (a b : Vec 32 Bool) :
    bvEq 32
      (bvOr 32
        (bvOr 32 (packA (s1v a b) (s0v a b))
          (bvShl 32 (zbyte (s2v a b) 24) 16))
        (bvShl 32 (zbyte (s3v a b) 24) 24))
      (bvAdd 32 a b) = true := by
  rw [bvEq_true_iff_BitVec_eq]
  rw [vecToBitVec_bvOr, vecToBitVec_bvOr, vecToBitVec_bvShl,
      vecToBitVec_bvShl, vecToBitVec_bvAdd, packA_img,
      zbyte_img (s2v a b) 24 (by omega), zbyte_img (s3v a b) 24 (by omega)]
  simp only [show (24 - 24 : Nat) = 0 from rfl, BitVec.ushiftRight_zero]
  -- Nat mask helpers
  have and255 : ∀ n : Nat, n &&& 255 = n % 256 := fun n => by
    simpa using Nat.and_two_pow_sub_one_eq_mod n 8
  have and65535 : ∀ n : Nat, n &&& 65535 = n % 65536 := fun n => by
    simpa using Nat.and_two_pow_sub_one_eq_mod n 16
  -- chained-division bridges (omega does not identify n / 65536 with
  -- n / 256 / 256 on its own)
  have hdd16 : ∀ n : Nat, n / 65536 = n / 256 / 256 := fun n => by omega
  have hdd24 : ∀ n : Nat, n / 16777216 = n / 256 / 256 / 256 := fun n => by
    omega
  -- toNat values of the partial sums, cleaned bottom-up (each strip's
  -- omega context stays free of deeper masked atoms)
  have g0 : (vecToBitVec (s0v a b)).toNat
      = (vecToBitVec a).toNat % 256 + (vecToBitVec b).toNat % 256 := by
    rw [s0v_img]
    simp only [BitVec.toNat_add, BitVec.toNat_and, BitVec.toNat_ofNat,
               Nat.reducePow, Nat.reduceMod, and255]
    omega
  have g1 : (vecToBitVec (s1v a b)).toNat
      = (vecToBitVec a).toNat / 256 % 256 + (vecToBitVec b).toNat / 256 % 256
        + (vecToBitVec (s0v a b)).toNat / 256 := by
    have hb0 : (vecToBitVec (s0v a b)).toNat < 65536 := by omega
    rw [s1v_img]
    simp only [BitVec.toNat_add, BitVec.toNat_and, BitVec.toNat_ushiftRight,
               BitVec.toNat_ofNat, Nat.reducePow, Nat.reduceMod,
               and255, and65535, Nat.shiftRight_eq_div_pow]
    rw [Nat.mod_eq_of_lt hb0]
    omega
  have g2 : (vecToBitVec (s2v a b)).toNat
      = (vecToBitVec a).toNat / 256 / 256 % 256
        + (vecToBitVec b).toNat / 256 / 256 % 256
        + (vecToBitVec (s1v a b)).toNat / 256 := by
    have hb1 : (vecToBitVec (s1v a b)).toNat < 65536 := by omega
    rw [s2v_img]
    simp only [BitVec.toNat_add, BitVec.toNat_and, BitVec.toNat_ushiftRight,
               BitVec.toNat_ofNat, Nat.reducePow, Nat.reduceMod,
               and255, and65535, Nat.shiftRight_eq_div_pow]
    rw [Nat.mod_eq_of_lt hb1, hdd16, hdd16]
    omega
  have g3 : (vecToBitVec (s3v a b)).toNat
      = (vecToBitVec a).toNat / 256 / 256 / 256 % 256
        + (vecToBitVec b).toNat / 256 / 256 / 256 % 256
        + (vecToBitVec (s2v a b)).toNat / 256 := by
    have hb2 : (vecToBitVec (s2v a b)).toNat < 65536 := by omega
    rw [s3v_img]
    simp only [BitVec.toNat_add, BitVec.toNat_and, BitVec.toNat_ushiftRight,
               BitVec.toNat_ofNat, Nat.reducePow, Nat.reduceMod,
               and255, and65535, Nat.shiftRight_eq_div_pow]
    rw [Nat.mod_eq_of_lt hb2, hdd24, hdd24]
    omega
  -- move the whole equation to Nat
  rw [BitVec.toNat_eq]
  simp only [BitVec.toNat_or, BitVec.toNat_shiftLeft, BitVec.toNat_and,
             BitVec.toNat_add, BitVec.toNat_ofNat, Nat.reducePow,
             Nat.reduceMod, and255]
  -- strip the shiftLeft mod-2^32 wrappers (every shifted byte is small)
  have hm1 : ((vecToBitVec (s1v a b)).toNat % 256) <<< 8 % 4294967296
      = ((vecToBitVec (s1v a b)).toNat % 256) <<< 8 :=
    Nat.mod_eq_of_lt (by rw [Nat.shiftLeft_eq]; omega)
  have hm2 : ((vecToBitVec (s2v a b)).toNat % 256) <<< 16 % 4294967296
      = ((vecToBitVec (s2v a b)).toNat % 256) <<< 16 :=
    Nat.mod_eq_of_lt (by rw [Nat.shiftLeft_eq]; omega)
  have hm3 : ((vecToBitVec (s3v a b)).toNat % 256) <<< 24 % 4294967296
      = ((vecToBitVec (s3v a b)).toNat % 256) <<< 24 :=
    Nat.mod_eq_of_lt (by rw [Nat.shiftLeft_eq]; omega)
  rw [hm1, hm2, hm3]
  -- disjoint ORs are sums
  rw [← Nat.shiftLeft_add_eq_or_of_lt
        (Nat.mod_lt _ (by decide) : (vecToBitVec (s0v a b)).toNat % 256 < 2 ^ 8)]
  rw [Nat.or_comm
        (((vecToBitVec (s1v a b)).toNat % 256) <<< 8
          + (vecToBitVec (s0v a b)).toNat % 256)
        (((vecToBitVec (s2v a b)).toNat % 256) <<< 16)]
  rw [← Nat.shiftLeft_add_eq_or_of_lt
        (show ((vecToBitVec (s1v a b)).toNat % 256) <<< 8
            + (vecToBitVec (s0v a b)).toNat % 256 < 2 ^ 16 by
          rw [Nat.shiftLeft_eq]; omega)]
  rw [Nat.or_comm
        (((vecToBitVec (s2v a b)).toNat % 256) <<< 16
          + (((vecToBitVec (s1v a b)).toNat % 256) <<< 8
            + (vecToBitVec (s0v a b)).toNat % 256))
        (((vecToBitVec (s3v a b)).toNat % 256) <<< 24)]
  rw [← Nat.shiftLeft_add_eq_or_of_lt
        (show ((vecToBitVec (s2v a b)).toNat % 256) <<< 16
            + (((vecToBitVec (s1v a b)).toNat % 256) <<< 8
              + (vecToBitVec (s0v a b)).toNat % 256) < 2 ^ 24 by
          rw [Nat.shiftLeft_eq, Nat.shiftLeft_eq]; omega)]
  simp only [Nat.shiftLeft_eq, Nat.reducePow]
  -- abstract the six toNat atoms so the closing arithmetic never
  -- defeq-compares the underlying towers
  clear hm1 hm2 hm3 and255 and65535 hdd16 hdd24
  generalize (vecToBitVec a).toNat = x at g0 g1 g2 g3 ⊢
  generalize (vecToBitVec b).toNat = y at g0 g1 g2 g3 ⊢
  generalize (vecToBitVec (s0v a b)).toNat = n0 at g0 g1 ⊢
  generalize (vecToBitVec (s1v a b)).toNat = n1 at g1 g2 ⊢
  generalize (vecToBitVec (s2v a b)).toNat = n2 at g2 g3 ⊢
  generalize (vecToBitVec (s3v a b)).toNat = n3 at g3 ⊢
  omega

end BADischarge

noncomputable def goal : Prop :=
  (a : Vec 32 Bool) -> (b : Vec 32 Bool) ->
  let a := (Pure.pure a); let b := (Pure.pure b);
  @Eq.{1} (Except String Bool)
    (Bind.bind
      (Bind.bind
        (Bind.bind (BADischarge.gAM a b)
          (fun v_1'''''' =>
            Bind.bind
              (Bind.bind
                (BADischarge.zbM 32 24 (by omega) (by omega)
                  (BADischarge.s2M a b))
                (fun v_1''''' => Pure.pure (bvShl 32 v_1''''' 16)))
              (fun v_2''' => Pure.pure (bvOr 32 v_1'''''' v_2'''))))
        (fun v_1'''''''' =>
          Bind.bind
            (Bind.bind
              (BADischarge.zbM 32 24 (by omega) (by omega)
                (BADischarge.s3M a b))
              (fun v_1''''''' => Pure.pure (bvShl 32 v_1''''''' 24)))
            (fun v_2'''' => Pure.pure (bvOr 32 v_1'''''''' v_2''''))))
      (fun v_1''''''''' =>
        Bind.bind
          (Bind.bind a (fun v_1 =>
            Bind.bind b (fun v_2 => Pure.pure (bvAdd 32 v_1 v_2))))
          (fun v_2''''' => Pure.pure (bvEq 32 v_1''''''''' v_2'''''))))
    (Pure.pure Bool.true)

theorem goal_holds : goal := by
  intro a b
  simp only [Pure.pure, Except.pure, BADischarge.s2M_ok, BADischarge.s3M_ok,
             BADischarge.gAM_ok, BADischarge.zbM_ok,
             Bind.bind, Except.bind, BADischarge.final_eq]
