ffs_bug.log: ffs.bc
ffs_bug_fail.log: ffs.bc
ffs_eq.log: ffs.bc
ffs_extract.log: ffs.bc
ffs_sat.log: ffs.bc
swap-simpler.log: xor-swap.bc
swap.log: xor-swap.bc
swap.log: xor-swap-bug.bc
swap.log: direct-swap.bc
swap_extract.log: swap-correct.bc
