/- Mandatory imports from saw-core-lean -/
import CryptolToLean
import CryptolToLean.SAWCorePrelude_proofs

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors

/- Code generated by saw-core-lean, then completed by a user proof. -/
namespace RecOnes
  noncomputable def allTrue : Except String (Stream Bool) :=
    Pure.pure
    (let stream_body_ := (fun lookup_ i_ => let s_ := (@Stream.MkStream Bool
    (fun (i : Nat) => atWithDefault 1 Bool (let scrut_ := (Stream.MkStream
    lookup_); @Stream.rec Bool (fun (strm' : Stream Bool) => Bool)
    (fun (s : Nat -> Bool) => s (subNat i 1)) scrut_) #v[Bool.true] i));
    streamIdx Bool s_ i_);
    let h_productivity_obligation_ : (Prop) := (StreamBodyProductive Bool
    stream_body_);
    let h_productivity_ : (h_productivity_obligation_) := by
      unfold h_productivity_obligation_ StreamBodyProductive
      intro i lookup₁ lookup₂ hlookup
      cases i with
      | zero => rfl
      | succ n =>
          dsimp [stream_body_, streamIdx, atWithDefault, subNat]
          exact hlookup n (Nat.lt_succ_self n)
    mkStreamFixChecked Bool (saw_unreachable_default Bool
    "fix lookup out of bounds") stream_body_ h_productivity_)

end RecOnes
