/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/- Code generated by saw-core-lean -/

noncomputable def goal : Prop :=
  (xs : Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) -> (ys : Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)) -> let xs := (Pure.pure
  xs); let ys := (Pure.pure ys); @Eq.{1} (Except String Bool) (Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)
  (let h_bounds_obligation_ : (Prop) := (LE.le (addNat
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  updSliceWithProof_checkedM (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) xs ys h_bounds_)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_) (fun v_1 => Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) Bool) ys
  CryptolToLean.SAWCorePrimitives.zero_macro h_bounds_) (fun v_2 => Pure.pure
  (bvEq (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_1 v_2)))) (Pure.pure
  Bool.true)

theorem goal_holds : goal := by
  intro xs ys
  simp only [natPos_macro, bit0_macro, one_macro, zero_macro,
    updSliceWithProof_checkedM, atWithProof_checkedM,
    Pure.pure, Bind.bind, Except.pure, Except.bind,
    Vector.getElem_ofFn]
  rw [dif_pos (show (2:Nat) * 1 ≤ 2 * 1 by omega),
      dif_pos (show (2:Nat) * 1 < 2 * 1 + 2 * (2 * 1) by omega)]
  simp only [Nat.sub_self, bvEq_refl]
