/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors
open CryptolToLean.SAWCoreBitvectorsProofs
open CryptolToLean.SAWCorePreludeProofs

/-
SLICE R2 ACCEPTANCE DISCHARGE - running_sum end-to-end.

Completed outline of the generated goal (drift-checked definitionally
against the tracked artifact): the vacuous bounds fallbacks are
stripped (omega closes every bound), the fix body is named via
RSDischarge.rsBody (definitionally the emitted lambda), and the
h_fix_prod_ placeholder is replaced by RSDischarge.rs_h_prod - the
PROVEN per-instance H_prod obligation (seed nonemptiness + element
totality + bounded lookback), established by unfolding the concrete
translated body against the library's genWithBoundsM_eq_ok /
atWithProof_gen_ok / iteM characterization lemmas. The realization
saw_fix_bounded_choose collapses to the closed-form prefix-sum vector
(rsSol) via saw_fix_bounded_choose_unique_pure_fixed_point, and the
goal reduces to the spec's unrolled bvAdd chain (bvAdd_id_l seam,
bvEq_refl close).
-/

/- Code generated by saw-core-lean -/

namespace RSDischarge

/-- The translated running_sum fix body, verbatim from the emitted
artifact (vacuous fallback branches stripped; every bound closes by omega),
parameterized over the wrapped input vector. -/
noncomputable def rsBody (xs : Except String (Vec 8 (Vec 32 Bool))) :
    Except String (Vec 9 (Vec 32 Bool)) → Except String (Vec 9 (Vec 32 Bool)) :=
  (fun (sums : Except String (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool))) => genWithBoundsM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  (fun (i' : Nat) (h_gen_bounds_ : LT.lt i'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) => CryptolToLean.SAWCorePreludeExtra.iteM
  (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (Pure.pure (ltNat i'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) (atRuntimeCheckedM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (vecSequenceM 1 (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) #v[Pure.pure (bvNat
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))))
  CryptolToLean.SAWCorePrimitives.zero_macro)]) i')
  (let h_bounds_obligation_ : (Prop) := (LT.lt (subNat i'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (genWithBoundsM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  (fun (i'' : Nat) (h_gen_bounds_ : LT.lt i''
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) => let x__ := (let h_bounds_obligation_ : (Prop) := (LT.lt
  i'' (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) UnitType)) (Bind.bind
  sums (fun v_4 => Bind.bind xs (fun v_5 => Pure.pure (zip (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) v_4 v_5)))) i'' h_bounds_);
  Bind.bind (Bind.bind x__ (fun v_2 => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) UnitType) v_2)))
  (fun v_1 => Bind.bind (Bind.bind (Bind.bind x__ (fun v_2 => Pure.pure
  (Pair_snd (Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (PairType (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) UnitType) v_2)))
  (fun v_2' => Pure.pure (Pair_fst (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) UnitType v_2')))
  (fun v_2'' => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2''))))) (subNat i'
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_)))

/-- One element of the closed-form step. -/
noncomputable def rsElem (x : Vec 8 (Vec 32 Bool)) (v : Vec 9 (Vec 32 Bool))
    (i : Nat) (hi : i < 9) : Vec 32 Bool :=
  if h : i < 1 then bvNat 32 0
  else bvAdd 32 (v[i - 1]'(by omega)) (x[i - 1]'(by omega))

/-- The closed-form step: what one rsBody application computes on a
pure input. -/
noncomputable def rsStep (x : Vec 8 (Vec 32 Bool)) (v : Vec 9 (Vec 32 Bool)) :
    Vec 9 (Vec 32 Bool) :=
  Vector.ofFn (fun i : Fin 9 => rsElem x v i.val i.isLt)

/-- v4.32.0 adaptation: the emitted term applies its selects at
macro-spelled 8 while the zip vector's type is `minNat 9 8`-spelled;
`Nat.min` is not reducible, so v4.32's tighter matching bridges the
two only at full transparency. This equation (which ELABORATES by
defeq — both sides' lengths are definitionally 8) rewrites the zip
node once into a consistently 8-spelled vector, after which the
original discharge script works unchanged. -/
theorem zip98_eq (v : Vec 9 (Vec 32 Bool)) (x : Vec 8 (Vec 32 Bool)) :
    zip (Vec 32 Bool) (Vec 32 Bool) 9 8 v x
      = (Vector.ofFn (fun i : Fin 8 =>
          PairType.PairValue (v[(i : Nat)]'(by omega))
            (PairType.PairValue (x[(i : Nat)]'i.isLt) UnitType.Unit))
         : Vec 8 (PairType (Vec 32 Bool) (PairType (Vec 32 Bool) UnitType))) := by
  apply Vector.ext
  intro i hi
  have hi8 : i < 8 := hi
  unfold zip
  simp [Vector.getElem_ofFn, Vector.get, hi8]
  exact (Vector.getElem_ofFn
    (f := fun i : Fin 8 =>
      PairType.PairValue (v[(i : Nat)]'(by omega))
        (PairType.PairValue (x[(i : Nat)]'i.isLt) UnitType.Unit))
    hi8).symm

theorem rsBody_pure_eq (x : Vec 8 (Vec 32 Bool)) (v : Vec 9 (Vec 32 Bool)) :
    rsBody (Pure.pure x) (Pure.pure v) = Pure.pure (rsStep x v) := by
  show rsBody (Except.ok x) (Except.ok v) = Except.ok (rsStep x v)
  unfold rsBody rsStep
  refine genWithBoundsM_eq_ok _ (rsElem x v) ?_
  intro i hi
  by_cases h1 : i < 1
  · have hi0 : i = 0 := by omega
    subst hi0
    simp [CryptolToLean.SAWCorePreludeExtra.iteM, ltNat, rsElem,
          atRuntimeCheckedM, Pure.pure, Bind.bind, Except.bind,
          Except.pure]
  · have hcond : ltNat i (natPos_macro one_macro) = false := by
      simp [ltNat_eq_decide_lt, h1]
    rw [hcond, iteM_pure_false]
    refine Eq.trans (atWithProof_gen_ok (n := 8) _
      (fun j hj => bvAdd 32 (v[j]'(by omega)) (x[j]'(by omega)))
      (subNat i (natPos_macro one_macro)) _ ?_) ?_
    · intro j hj
      -- v4.32.0: the zip-select sits at the minNat-spelled bound and simp
      -- no longer bridges `j < 8` to it on its own;
      -- instantiate the ofFn read explicitly.
      simp [Pure.pure, Bind.bind, Except.bind, Except.pure,
            atWithProof_checkedM, zip98_eq, Vector.getElem_ofFn,
            Pair_fst, Pair_snd, Vector.get]
    · simp [rsElem, h1]

/-- H_prod for the running_sum body — every field by unfolding the
concrete body (amendment A: proven, never assumed). -/
theorem rs_h_prod (x : Vec 8 (Vec 32 Bool)) :
    saw_fix_bounded_productive 9 (Vec 32 Bool) (rsBody (Pure.pure x)) := by
  refine ⟨⟨Vector.replicate 9 (bvNat 32 0)⟩, ?_, ?_⟩
  · intro v
    exact ⟨rsStep x v, rsBody_pure_eq x v⟩
  · intro v₁ v₂ w₁ w₂ h₁ h₂ i hi hpre
    have e₁ : w₁ = rsStep x v₁ := by
      have h := (rsBody_pure_eq x v₁).symm.trans h₁
      exact ((Except.ok.injEq _ _).mp h).symm
    have e₂ : w₂ = rsStep x v₂ := by
      have h := (rsBody_pure_eq x v₂).symm.trans h₂
      exact ((Except.ok.injEq _ _).mp h).symm
    subst e₁ e₂
    unfold rsStep
    simp only [Vector.getElem_ofFn, rsElem]
    by_cases h1 : i < 1
    · simp [h1]
    · simp only [h1, dif_neg, not_false_iff]
      have hv : v₁[i - 1]'(by omega) = v₂[i - 1]'(by omega) :=
        hpre (i - 1) (by omega) (by omega)
      rw [hv]

/-- The closed-form solution chain: `rsChain k = 0 + x0 + … + x(k-1)`. -/
noncomputable def rsChain (x : Vec 8 (Vec 32 Bool)) : Nat → Vec 32 Bool
  | 0 => bvNat 32 0
  | k + 1 =>
    if h : k < 8 then bvAdd 32 (rsChain x k) (x[k]'h)
    else rsChain x k

/-- The closed-form solution vector. -/
noncomputable def rsSol (x : Vec 8 (Vec 32 Bool)) : Vec 9 (Vec 32 Bool) :=
  Vector.ofFn (fun i : Fin 9 => rsChain x i.val)

/-- The closed form is a fixed point of the body. -/
theorem rs_sol_fixed (x : Vec 8 (Vec 32 Bool)) :
    rsBody (Pure.pure x) (Pure.pure (rsSol x)) = Pure.pure (rsSol x) := by
  rw [rsBody_pure_eq]
  -- with the index space fully concrete (n = 9), both `ofFn` vectors
  -- evaluate to definitionally equal literals element-by-element
  show Except.ok (rsStep x (rsSol x)) = Except.ok (rsSol x)
  congr 1

/-- The emitted realization collapses to the closed form. -/
theorem rs_choose_eq (x : Vec 8 (Vec 32 Bool))
    (H : saw_fix_bounded_productive 9 (Vec 32 Bool) (rsBody (Pure.pure x))) :
    saw_fix_bounded_choose 9 (Vec 32 Bool) (rsBody (Pure.pure x)) H =
      Pure.pure (rsSol x) :=
  (saw_fix_bounded_choose_unique_pure_fixed_point 9 (Vec 32 Bool)
    (rsBody (Pure.pure x)) H (rsSol x) (rs_sol_fixed x)).symm

end RSDischarge

noncomputable def goal : Prop :=
  (xs0 : Vec (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)) -> let xs := (Pure.pure
  xs0); @Eq.{1} (Except String Bool) (Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) (genWithBoundsM
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  (fun (i : Nat) (h_gen_bounds_ : LT.lt i
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))))) => let h_bounds_obligation_ : (Prop) := (LT.lt
  (subNat (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) i)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool)
  (let fix_body_ := (RSDischarge.rsBody xs);
  let h_fix_prod_obligation_ : (Prop) := (saw_fix_bounded_productive
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) fix_body_);
  let h_fix_prod_ : (h_fix_prod_obligation_) := ((RSDischarge.rs_h_prod xs0));
  saw_fix_bounded_choose (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) fix_body_ h_fix_prod_)
  (subNat (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) i) h_bounds_))
  CryptolToLean.SAWCorePrimitives.zero_macro h_bounds_)
  (fun v_1''''''' => Bind.bind (Bind.bind (Bind.bind (Bind.bind (Bind.bind
  (Bind.bind (Bind.bind (Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  CryptolToLean.SAWCorePrimitives.zero_macro
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  CryptolToLean.SAWCorePrimitives.zero_macro h_bounds_) (fun v_1 => Bind.bind
  (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro)
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  CryptolToLean.SAWCorePrimitives.one_macro) h_bounds_) (fun v_2 => Pure.pure
  (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1 v_2))))
  (fun v_1' => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_) (fun v_2' => Pure.pure
  (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1' v_2'))))
  (fun v_1'' => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)) h_bounds_) (fun v_2'' => Pure.pure
  (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1'' v_2''))))
  (fun v_1''' => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_)
  (fun v_2''' => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1''' v_2'''))))
  (fun v_1'''' => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_)
  (fun v_2'''' => Pure.pure (bvAdd (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1'''' v_2''''))))
  (fun v_1''''' => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_)
  (fun v_2''''' => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1''''' v_2'''''))))
  (fun v_1'''''' => Bind.bind (let h_bounds_obligation_ : (Prop) := (LT.lt
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))));
  let h_bounds_ : (h_bounds_obligation_) := ((by (try unfold h_bounds_obligation_); (first | assumption | omega | (simp only [natPos_macro, bit0_macro, bit1_macro, one_macro, zero_macro, succ_macro, subNat, addNat, mulNat, minNat, maxNat, divNat_eq_div, modNat_eq_mod, divNat_checked_eq_div, modNat_checked_eq_mod, Nat.sub_eq, Nat.add_eq, Nat.mul_eq] at *; omega) | skip)));
  atWithProof_checkedM (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))) (Vec
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) Bool) xs
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  (CryptolToLean.SAWCorePrimitives.bit1_macro
  CryptolToLean.SAWCorePrimitives.one_macro))) h_bounds_)
  (fun v_2'''''' => Pure.pure (bvAdd
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1'''''' v_2''''''))))
  (fun v_2''''''' => Pure.pure (bvEq
  (CryptolToLean.SAWCorePrimitives.natPos_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  (CryptolToLean.SAWCorePrimitives.bit0_macro
  CryptolToLean.SAWCorePrimitives.one_macro)))))) v_1''''''' v_2'''''''))))
  (Pure.pure Bool.true)

theorem goal_holds : goal := by
  intro xs0
  simp only [natPos_macro, bit1_macro, bit0_macro, one_macro,
             zero_macro, subNat, Nat.reduceMul, Nat.reduceAdd]
  simp only [RSDischarge.rs_choose_eq]
  simp [atWithProof_checkedM, genWithBoundsM, Pure.pure, Bind.bind,
        Except.bind, Except.pure, RSDischarge.rsSol, RSDischarge.rsChain,
        bvAdd_id_l, bvEq_refl]