/- Mandatory imports from saw-core-lean -/
import CryptolToLean

open CryptolToLean.SAWCorePrimitives
open CryptolToLean.SAWCoreVectors

/- Code generated by saw-core-lean, then completed by a user proof.

The generated mutual-stream body is factored into named definitions before the
local productivity evidence. This keeps the completed outline definitionally
equivalent to the lowered `mkStreamFixPairChecked` shape while avoiding large
inline reductions in the side-condition proofs. -/
namespace StreamFibs

abbrev Word := Vec 32 Bool

noncomputable def defaultWord : Word :=
  saw_unreachable_default Word "fix lookup out of bounds"

noncomputable def bodyA
    (_lkA lkB : Nat → Word) (i : Nat) : Word :=
  atWithDefault 1 Word (lkB (subNat i 1)) #v[bvNat 32 0] i

noncomputable def bodyB
    (lkA lkB : Nat → Word) (i : Nat) : Word :=
  atWithDefault 1 Word
    (bvAdd 32 (lkA (subNat i 1)) (lkB (subNat i 1)))
    #v[bvNat 32 1] i

theorem bodyA_productive :
    PairStreamComponentProductive Word Word Word bodyA := by
  unfold PairStreamComponentProductive
  intro i lookupα₁ lookupα₂ lookupβ₁ lookupβ₂ _hα hβ
  cases i with
  | zero => rfl
  | succ n =>
      dsimp [bodyA, atWithDefault, subNat]
      exact hβ n (Nat.lt_succ_self n)

theorem bodyB_productive :
    PairStreamComponentProductive Word Word Word bodyB := by
  unfold PairStreamComponentProductive
  intro i lookupα₁ lookupα₂ lookupβ₁ lookupβ₂ hα hβ
  cases i with
  | zero =>
      simp [bodyB, atWithDefault]
  | succ n =>
      simp [bodyB, atWithDefault, subNat,
        hα n (Nat.lt_succ_self n), hβ n (Nat.lt_succ_self n)]

noncomputable def fibsPair : PairType (Stream Word) (Stream Word) :=
  mkStreamFixPairChecked Word Word defaultWord defaultWord
    bodyA bodyB bodyA_productive bodyB_productive

noncomputable def streamFibs
    (x : Except String (Vec 8 Bool)) : Except String Word :=
  Bind.bind x (fun idx =>
    Pure.pure
      (streamIdx Word (pairFst (Stream Word) (Stream Word) fibsPair)
        (bvToNat 8 idx)))

end StreamFibs
